### ISSUE TITLE
Ignoring comments

### ISSUE THREAD

**Issue by cod3monk** [eliben/pycparser#102]
Would you accept a pull request which leads to ignoring comments rather than failing on them?

**Comment by eliben** [comment]
What would be the goal of that? Macros would fail anyway, right?

Perhaps as a separate pre-processing step?

**Comment by cod3monk** [comment]
To allow users of my package to have comments within their code, without pycparser complaining about it. I would just ignore them on the parser side.
Of cause I could just filter them out before handing the code to pycparser, but I suppose other people would find it useful as well.

**Comment by eliben** [comment]
My question was - you expect users to pass unpreprocessed code through to pycparser? What about macros and other preprocessor-y things ("\" line endings, etc.), what happens to these?

I'd prefer to maintain separate preprocessing from parsing for now. Therefore, I could see a separate something added to filter out C/C++ comments that could optionally be run before the parsing happens
