### ISSUE TITLE
The correct way to parse multiple files and treat the resulting trees as a whole?

### ISSUE THREAD

**Issue by dubslow** [eliben/pycparser#104]
So if we want to parse a large library and consider it as one large syntax tree, how do we go about this?

I've briefly examined the code, and it looks like the following should suffice:

```
ast = FileAST()
for f in files:
    ast.ext += CParser().parse(file, ...).ext
do_things_with_ast(ast)
```
Is this the "correct" way to go about it? Is there something that this will break? (Besides the coord attribute which appears to be unused as far as I can tell)

**Comment by eliben** [comment]
This looks reasonable, but why would you want to do this? Typically, a single C translation unit gets parsed into a single AST. All kinds of C semantics rely on that (for example variable redefinitions being invalid within a single TU but valid across TUs)

**Comment by dubslow** [comment]
I'm trying to write software to automatically generate a call-chain tree, and flow control passes between all the files in a project, so... I need to treat the project as a whole in some manner.

I suppose I'll proceed in this way and let you know of any issues I encounter.

(With my current test project, I'm having difficulties trying to define away the inline asm.)
