### ISSUE TITLE
Strings with embedded newlines aren't lexed correctly

### ISSUE THREAD

**Issue by mpbeede** [eliben/pycparser#105]
Checked against commit fd2c7731c4d4cd225fe0a47fe6de6f528f22842c 

A string continued with a backslash doesn't seem to parse.  A short example is attached.  Perhaps C99 doesn't actually allow this?

[foo.c.txt](https://github.com/eliben/pycparser/files/38348/foo.c.txt)

**Comment by eliben** [comment]
I believe backslash-ending lines should be handled by the preprocessor, and hence shouldn't be visible to pycparser.

**Comment by mpbeede** [comment]
I had a feeling I was missing something obvious, and that is in fact it.  Sorry to bother you with it.


Regards,


     Mike Beede


________________________________


I believe backslash-ending lines should be handled by the preprocessor, and hence shouldn't be visible to pycparser.

-

**Comment by kirbyfan64** [comment]
@eliben is correct; I just tried it. `cpp` and `mcpp` both remove it.
