### ISSUE TITLE
struct t_some {int Foo;}  var1,var2;

### ISSUE THREAD

**Issue by jdla** [eliben/pycparser#112]
Dear,

When the input contains the construction in subject, c_generator transforms to 

```
struct t_some
{
int Foo;
} var1;
struct t_some
{
int Foo;
} var2;
```
Which doesn't compile.
Is this an issue or am I doing something wrong ?

**Comment by kirbyfan64** [comment]
What was the input?

**Comment by jdla** [comment]
[transfer.zip](https://github.com/eliben/pycparser/files/126170/transfer.zip)

**Comment by jdla** [comment]
By the way, it generates three other compile errors as well in the translation. The compile log is hereto attached. I know it is pathetic code, but that's why I need some rework on it :)
[x.zip](https://github.com/eliben/pycparser/files/126192/x.zip)

**Comment by jdla** [comment]
Hey, I wanted to share the changes that I made to generator and that seem to do the trick to compile that beast correctly. Changes are indicated with "JDLA". It's not exactly the original file, but you will recognize easily.
I am not 100% sure to have it all correct, but it looks so and at least I understood the things I did :)
[dlGenerator.py.zip](https://github.com/eliben/pycparser/files/126305/dlGenerator.py.zip)

**Comment by jdla** [comment]
Forgot to mention : correct, except for the struct issue, that's a harder one.

**Comment by eliben** [comment]
Please submit a pull request with your proposed fix, along with tests

**Comment by jdla** [comment]
I am really sorry, but I am not familiar with git , pull requests , neither do I have a set-up for the moment to do so.

I understand you'd prefer a more structured submission of the problem and fix, but that won't work for the moment. Meanwhile above stuff works for me and I wanted to share nevetheless as a courtesy.

Great application by the way !

**Comment by eliben** [comment]
I had a bit of time to check, and the produced code here (with `var` and `var2` going into separate decls) is correct - no parse error due to it.

It is a fact of life with C-to-C translation in pycparser that some syntactic (concrete syntax) information gets lost when parsing to AST. As long as the produced code still compiles and is logically equivalent, I think this is working as intended.
