### ISSUE TITLE
Wrong path in using_gcc_E_libc.py

### ISSUE THREAD

**Issue by akhtyamovrr** [eliben/pycparser#113]
In using_gcc_E_libc.py there is a wrong path to file used in this example.
{code}filename = 'examples/c_files/year.c'{code}
Can be fixed by changing path to 'c_files/year.c'

**Comment by eliben** [comment]
Thanks for the report. Would you like submitting a pull request to fix this?

**Comment by akhtyamovrr** [comment]
Yes, I'm on it

**Comment by akhtyamovrr** [comment]
https://github.com/eliben/pycparser/pull/114
