### ISSUE TITLE
Potential embedded domain compiler issues

### ISSUE THREAD

**Issue by fkromer** [eliben/pycparser#123]
#In the domain of embedded system development there are a lot of microprocessor specific compilers available. About what potential issues do i have to think about when i want to preprocess c files with these specific compilers instead of using cpp ([or gcc or clang](https://github.com/eliben/pycparser#31interaction-with-the-c-preprocessor)). It seems like there is a lot potential for issues related to extensions and configuration e.g. with MSVC #91.

**Comment by Syeberman** [comment]
Eli wrote an excellent article here: http://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/.

**Comment by fkromer** [comment]
Thanks a lot for the hint! Knowing about *fake headers*, *blocking of pre-set system header include directories* and *defining away uninteresting stuff* should help...
