### ISSUE TITLE
The typedefs and other definitions from fake_libc_include conflicts with the actual defines (parsing sqlite.c).

### ISSUE THREAD

**Issue by vrthra** [eliben/pycparser#127]
I am trying to parse sqlite.c (amalgamated), and reprint the AST using the `examples/c-to-c.py`. My environment is `Ubuntu 15.04` with `gcc 4.9.2`.  I am using `sqlite 3.13`. My makefile is below.

```
sqlite.c: c/sqlite3.c c/sqlite3.h utils/fake_libc_include/_fake_defines.h
	gcc -nostdinc -D'__attribute__(x)=' -I utils/fake_libc_include/ -E c/sqlite3.c -Ic/ > sqlite.c_
	mv sqlite.c_ sqlite.c

s.c: sqlite.c
	python3 ./examples/c-to-c.py sqlite.c > s.c_
	mv s.c_ s.c

s: s.c
	gcc s.c c/shell.c -o s
```

On running the `gcc s.c` command, it fails with

```
s.c:3:13: error: conflicting types for ‘__builtin_va_list’
 typedef int __builtin_va_list;

s.c:2816:22: note: expected ‘struct __va_list_tag *’ but argument is of type ‘int’
s.c:2843:25: error: expected ‘,’ before ‘)’ token
     *__builtin_va_arg(ap) = val;
                         ^

```
and
```
s.c:3192:5: error: dereferencing pointer to incomplete type
     *pTm = *pX;
     ^
s.c:3192:12: error: dereferencing pointer to incomplete type
     *pTm = *pX;
            ^
s.c: In function ‘localtimeOffset’:
s.c:3204:13: error: storage size of ‘sLocal’ isn’t known
   struct tm sLocal;
             ^
```

I assumed from the `Changelog` that I would be able to parse and reprint the AST of `sqlite.c`. Is it supported?

**Comment by Syeberman** [comment]
I'd advise against compiling code using `fake_libc_include`.  This file is intended strictly to help pycparser parse the code a little easier.  For example, all the sized-integer types like `int8_t` are just typedef'd to `int`, which is definitely _not_ what you want.

It looks like you want to programmatically modify the source code before compiling?  This would be tricky with `pycparser`, perhaps using the location information in the AST to modify a copy of the original source file on disk.  I haven't personally done this.

**Comment by dmurdin** [comment]
I had a similar problem, where I have very many different compilers, and do not want to handle all variations in header-files while parsing,  so I use the fake headers. At the same time I want to use real headers when compiling  rewritten c-code.

I found https://github.com/akiradeveloper/macro-of-inline that uses pycparser to rewrite code. In cppwrap.py, function Apply, include-directives are restored to the output c-file by analyzing line-directives in preprocessed source (make sure to enable line-directives in preprocessor output), and also generating a separate AST for the included code that is then removed.

That version has some limitations, so I have an updated version that can handle mixing of comments/preprocessor-code and include-statements and also can handle superfluos includes, that the original cannot handle. It  is available in 
https://github.com/dmurdin/macro-of-inline (again in cppwrap.py/Apply). Note your code is still preprocessed except for include-directives so if you e.g. have preprocessor-macros with varying behaviour affected by includes, you could still have problems.

Would perhaps be nice if some write-c-with-restored-includes-function could be made part of pycparser proper.

**Comment by eliben** [comment]
Closing this as I don't believe this is a real problem with pycparser, rather it's just a matter of expectations. Feel free to ping if you think otherwise - or better yet open a more specific issue.

**Comment by batz003** [comment]
So is it wrong to expect pycparser's output to be compileable, and running just as the initial c code?

**Comment by eliben** [comment]
@batz003 Yes, pycparser can lose information -- especially about the types. You can achieve full end-to-end transform and compile with some effort, but it's not something promised out of the box
