### ISSUE TITLE
code-generation for ternary operator

### ISSUE THREAD

**Issue by dmurdin** [eliben/pycparser#131]
I had problems with operator precedence when generating code for the ternary operator, original code such as:
`(X == 0) ? (Y=1) : (Y=2)`
which became after parsing and code generation:
`X == 0 ? Y=1 : Y=2`
which causes a compilation error since last assignment has lower precedence, essentially becoming
`(X == 0 ? Y=1 : Y) = 2`
I fixed this in in c_generator.py by modding to:
`    def visit_TernaryOp(self, n):`
`        s  = '(' + self._visit_expr(n.cond) + ') ? '`
`        s += '(' + self._visit_expr(n.iftrue) + ') : '`
`        s += '(' + self._visit_expr(n.iffalse) + ')'`
`        return s
`

**Comment by eliben** [comment]
Sounds reasonable - please submit a PR to fix this
