### ISSUE TITLE
Expanding included libraries may lead to duplicate typedefs

### ISSUE THREAD

**Issue by ogrady** [eliben/pycparser#137]
Expanding libraries that contain `typedefs` that are the same as defines in the including file cause errors when passing the file to `gcc`. 
Possible solution: save the includes, let pycparser do it's thing then remove the expanded typedefs and reinsert the includes.

**Comment by eliben** [comment]
I'm not sure I understand the problem, to be honest. Can you provide a simple example?

**Comment by ogrady** [comment]
Not sure if I can provide a good example, since this might be specific to OS X (some errors include "__darwin*").
Putting a simple HelloWorld-program through CParser and CGenerator outputs the same program with it's dependencies extended (as expected).
Running GCC on that program then yields errors
![screen shot 2016-08-12 at 07 54 20](https://cloud.githubusercontent.com/assets/5565560/17613887/0ddf3542-6062-11e6-94d8-c95d449a3dda.png)

I found that I can avoid those errors when I add another step which replaces the expanded libraries with the includes again before printing out the code.

**Comment by eliben** [comment]
If you actually intend to run C code with faked includes (which is where that `__builtin_va_list` came from ISTM), and then feed it back to gcc, you better not emit the typedefs for the fake includes. I'd walk the AST and just kill those typedefs prior to putting the AST through `CGenerator`.

**Comment by ogrady** [comment]
That's basically what I did. But since this seems like a step everybody(?) has to through I wondered if this doesn't deserve it's own library-function.

**Comment by eliben** [comment]
I actually haven't encountered this issue before. Also, I'm trying to reduce the scope of pycparser to the parsing side. The C generation side has a huge number of possibilities to expand it, but pycparser can't do that all
