### ISSUE TITLE
Parser doesn't seem to visit all occurrences of some nodes

### ISSUE THREAD

**Issue by ogrady** [eliben/pycparser#138]
To reproduce create a visitor which counts all occurrences of Ifs for a nested file like https://github.com/TiarkRompf/legobase-micro/blob/master/minidb/cqueries/Q1.c

Then count all "if (" using grep or a texteditor.

**Comment by eliben** [comment]
Can you create a minimal reproducing example?

**Comment by ogrady** [comment]
Use on the file provided in the first comment.
http://pastebin.com/yLgRCBGq

**Comment by eliben** [comment]
I meant an input file smaller than 1100 lines :)

Also could this be due to #136? Maybe nested if statements are the issue?

**Comment by ogrady** [comment]
Yes, that seems to be the problem. Adding `self.generic_visit(node)` to the end of function solves this.
