### ISSUE TITLE
Fault report for non-psychics

### ISSUE THREAD

**Issue by Derek-Jones** [eliben/pycparser#139]
The blog post:
http://shape-of-code.coding-guidelines.com/2016/02/08/pycparser-a-serious-entry-in-the-not-written-in-c-c-parser-category/

discusses pycparser and lists some faults.  The faults appear to be in the latest release.

Ok, you are not psychic and I should have reported them earlier.

**Comment by eliben** [comment]
Thanks for using pycparser for this. Unfortunately I don't think I'll find time to dig in the logs of your test runs. If you could open some issues for the most critical faults in your eyes, that would be very helpful.

**Comment by Derek-Jones** [comment]
I went through the log of messages and pulled out the 'real' faults before writing the article, linked to under "failed to handle...": http://www.coding-guidelines.com/code-data/pyparse-fails.txt  These are all things that should be handled, but are not.

I would say the most critical fault is pycparser's habit of failing and producing trace-back when it gets confused by some weird input.  Skip to semicolon is a surprisingly good error recovery strategy.

You could probably get away with ignoring the unsupported features I found.  But poor error recovery is very unfriendly.

**Comment by eliben** [comment]
Yes, pycparser isn't great with error recovery, and that has never been the goal. I was always intending pycparser to parse code that we know is correct, *because* its error reporting and recovery are pretty bad. This is because of its architecture using a LALR parser generated from a yacc-like tool; these tools are usually known for fairly poor error reporting because of the lost context in the bottom-up parsing process.

**Comment by Derek-Jones** [comment]
The problem is not loss of context,, the problem is the compression algorithms used to create really small parser tables throws nearly all the context away.

It is possible to do reasonably good error recovery with LALR parsers.  Not much gets written about this; I will add it to my list of possible blog articles.

**Comment by eliben** [comment]
Closing this; feel free to open more concrete reports. However, precise error reporting is not a high priority for pycparser.
