### ISSUE TITLE
Get the parent node when overriding the 'c_ast.NodeVisitor'

### ISSUE THREAD

**Issue by wangcong15** [eliben/pycparser#140]
How could i get the parent node when overriding the 'c_ast.NodeVisitor'. The subclasses of 'Node' have 'children' an attribute. But sometimes i need link to the parent node. Is there any possible solutions?

**Comment by eliben** [comment]
Please refer to this FAQ: https://github.com/eliben/pycparser/wiki/FAQ#why-dont-ast-nodes-in-pycparser-have-parent-links
