### ISSUE TITLE
sys/types.h missing from fakelibc?

### ISSUE THREAD

**Issue by zubinmeva** [eliben/pycparser#142]
kept getting 'sys/types.h' file not found errors.

I assume this is a standard header

Thanks

**Comment by w-vi** [comment]
`sys/types.h` it's not standard, it's posix.

**Comment by eliben** [comment]
Have you read https://github.com/eliben/pycparser#32what-about-the-standard-c-library-headers ?

pycparser's `fake_libc_headers` directory does carry `sys/types.h`

**Comment by zubinmeva** [comment]
Yes I had read that and the blog post. wonder why i can't find it. i can see a _fake_typedefs.h

did you mean the `fake_libc_include` directory?

**Comment by eliben** [comment]
https://github.com/eliben/pycparser/blob/master/utils/fake_libc_include/sys/types.h

**Comment by zubinmeva** [comment]
Thanks so much Eli. I think my issue might have been that installed
pycparser from the debian repo.
