### ISSUE TITLE
cryptography build fails with pycparser==2.14

### ISSUE THREAD

**Issue by skoval00** [eliben/pycparser#149]
cryptography build fails with pycparser==2.14 with
`AssertionError: sorry, but this version only supports 100 named groups`
[Traceback](http://pastebin.com/L0Z1wr2n)

I suppose the problem may be in regular expression in `pycparser.lextab._lexstatere`

**Comment by jayvdb** [comment]
See #147

**Comment by skoval00** [comment]
Oh! Thank you.
