### ISSUE TITLE
Discussion: Possible improvements to the AST?

### ISSUE THREAD

**Issue by burnpanck** [eliben/pycparser#150]
Disclaimer: These are difficulties that I encountered while working on a [feature](https://github.com/burnpanck/pycparser/tree/feature-exact-char-range-coords) intended to provide character exact coordinates for the AST nodes. I want to use this place to discuss these, rather than to state that there is a need to change the AST.

First of all, I think there is some lack of documentation of the AST. The source files essentially do not contain any information on how the AST nodes are supposed to be nested. This makes the learning curve for users (like me) of the parser output a bit steeper. I am currently slowly learning by example, and I will try to change the AST node classes to encode that information in a way that does not break anything.

Apart from that, I am aware that any change in the structure of the AST could cause some backwards compatibility headaches to existing users. Nevertheless, there are two things that I would possibly change if I was to redesign the AST.

Both issues are related to type declarations. The first is simple: In quite a few cases, AST nodes store more than one string/token, i.e. a `Decl` has `qual`, `storage` and `declname`. Thus, there is no place to record my metadata, the source location of these particular words. Wrapping them into their own `ID` or similar would of course solve that.

My second issue is with `TypeDecl`, but it's possibly just an issue with my current understanding of the AST structure. Intuitively I'd say there should be an AST node indicating that we are declaring something to have a particular type, e.g. a variable (`Decl`) or another a type alias (`Typedef`). These nodes should contain nodes that actually describe the type. With, `PtrDecl` and `ArrayDecl` I'm happy. But what does `TypeDecl` do? From what I understand, it's simply a wrapper for `Struct`,  `Union` and `IdentifierType`(what about `Enum`?). But to me, it does not add any value. It does act as a container to store the `declname` but that has nothing to do with the actual type! It is merely a relic from the way the AST is collected by the parser, where of course the innermost type usually is parsed at the outermost level of syntax, but the name which mainly belongs to the outermost part is parsed at the innermost level. It appears to me that `TypeDecl` could simply be left out, or am I missing something here?

**Comment by burnpanck** [comment]
I'm continuing to try to understand the AST. I wrote a node visitor that collects the set of object types that appear for each attribute of each ast node type. Here are a few pecularities I observed, when I extract the statistics for every parse happening during `test_c_parser.py`:

- `ID`: Appears mostly as a reference to existing name, most of the time acting as an expression. However, it also appears in `field` of `StructRef`, where it doesn't really represent an expression on it's own, but at least a reference to an existing name. Furthermore, it appears in the `name` of other `ID`'s, which sounds like a bug to me.

- `Decl`/`TypeDecl`: As described in my previous comment, it appears that there are two tiers of type describing nodes: The first tier is `ArrayDecl`,`PtrDecl`,`FuncDecl`, which can be nested among each other and may additionally contain `TypeDecl`. `TypeDecl` acts as gateway to the second tier, consisting of `Enum`, `Union`, `Struct` and `IdentifierType`. However, the `type` attribute of `Decl` doesn't seem to conform to that separation, it may contain nodes of either tier. It appears to me that `Decl` is possibly covering multiple distinct concepts, which leads to an unclear meaning of that node.

**Comment by eliben** [comment]
You're absolutely correct in that the AST won't change at this point; this will break many users at no big advantage. There are some idiosyncrasies courtesy of the C grammar, but sometimes these are actually warranted. I suggest to grep through the parser tests to see some unusual situations.

As for adding metadata - it's entirely possible. AST nodes are just Python objects and you can easily add more attributes to them.
