### ISSUE TITLE
Wrong file permissions?

### ISSUE THREAD

**Issue by jnbr** [eliben/pycparser#154]
Is it intentional, that files in the 2.16 release are not world readable?

**Comment by eliben** [comment]
Can you clarify which files this is about?

**Comment by jnbr** [comment]
This is about all files in the tarball and also affects the installed files in
`/usr/lib/python2.7/site-packages/pycparser-2.16-py2.7.egg-info`

I detected it because of this exception, when trying to run ansible-playbook:
`ERROR! Unexpected Exception: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser-2.16-py2.7.egg-info/PKG-INFO'`

**Comment by eliben** [comment]
I have no idea why this happened, to be honest.

**Comment by kirbyfan64** [comment]
@eliben Could it be the same issue as [this](https://bugs.launchpad.net/dateutil/+bug/1243202)? Maybe you ran `setup.py dist` as `sudo` or something...

**Comment by eliben** [comment]
*sigh* Python packaging

**Comment by xdesai** [comment]
I am running into this same issue. Any chance of a fix?

**Comment by eliben** [comment]
@xdesai can you give more details on how the issue is affecting you?

**Comment by xdesai** [comment]
Somewhere between 2.15 and 2.16 the file permissions for the files described by @jnbr got changed. So when I install pycparser and then try to run code using it as a non-root user I get permission errors.
Downgrading to 2.15 fixed the issue for me cuz the file permissions are universally readable.
This is the source tarball from pypi btw.

**Comment by kirbyfan64** [comment]
I swear, this 2.1x line is cursed or something. :)

**Comment by eliben** [comment]
I created a new tarball for 2.17 where the permissions should be ok -- [pycparser-2.17.tar.gz](https://github.com/eliben/pycparser/files/557498/pycparser-2.17.tar.gz)

Please help me verify this tarball is OK -- that you can pip install pycparser from it and everything works as you expect. Once that's done I can push it to PyPI.

**Comment by jnbr** [comment]
I haven't checked with pip but running `setup.py install` works for me

**Comment by eliben** [comment]
@jnbr trying with pip would be greatly appreciated :) It's really exercising more of the "real" system, and is even easier than running `setup.py` in a virtualenv (no need to untar the tarball)

**Comment by xdesai** [comment]
I don't think pip was ever an issue actually. Pip will reset the file permissions and setup.py will not. This is why I had issues in the first place. 
I just verified the permissions are now what I expect. Thanks for making this fix!

**Comment by eliben** [comment]
@xdesai thanks for checking. I didn't know the problem was only with `setup.py` in this case; it makes sense since the number of reports is so small :) [all the heavy users of pycparser use pip]

**Comment by jnbr** [comment]
Just to make sure, I checked pip too now. No issues there.

Yes, most people probably use pip but there are some package managers which use the plain `setup.py` to handle python packages.

**Comment by eliben** [comment]
Thanks for the testing. I pushed release 2.17 to PyPI

**Comment by jnbr** [comment]
Since the issue is solved with release 2.17, I will close this issue.
