### ISSUE TITLE
pip install misses "fake_libc_include" directory

### ISSUE THREAD

**Issue by j1elo** [eliben/pycparser#157]
I've followed the installation instructions by doing:
`sudo pip install pycparser`
on a Ubuntu 14.04 machine, and pycparser version 2.17 gets correctly installed but the installation is completely missing the "fake_libc_include" directory.
I expected that this directory would be installed as the documentation seems to assume that this will be the case.

**Comment by eliben** [comment]
I don't know if it makes sense to install these files into `site-packages` since they're not Python packages and are just a supplementary util. It's best to unzip them from the source distribution or have a clone of the git repo somewhere

**Comment by Syeberman** [comment]
I personally just copy the versions from [GitHub](https://github.com/eliben/pycparser/tree/master/utils/fake_libc_include) directly into my project.  It allows me to change the headers as needed.

**Comment by eliben** [comment]
@Syeberman I think this is the right way to do it. The fake headers were never meant to be a "single source of truth" living in the `site-packages` ivory tower. It's just a way to make pycparser handle new code-bases, and I expect users to continuously tweak them.

**Comment by j1elo** [comment]
Ok then this was just a small communication problem from the installation instructions; the part "2.2   Installation process" points to two methods which I understood would be equivalent in all ways, but they aren't. Choosing to use pip still requires to download the ZIP package from Github if the fake headers are to be used; maybe this could be stated in the manual, it would clarify this detail.

**Comment by eliben** [comment]
@j1elo Sounds good - can you submit a PR to rephrase that?
