### ISSUE TITLE
Parser's wrong interpretation of expression containing {0} and casting

### ISSUE THREAD

**Issue by rachelhac** [eliben/pycparser#164]
when parsing the following line:
**void* ptr = (int[ ]){0};**

The parser doesn't interpret it correctly (doesn't identify the casting and doesn't understand the initialization of new array) and create the following AST node for it:

Decl: ptr, [], [], []
        PtrDecl: []
          TypeDecl: ptr, []
            IdentifierType: ['void']
        CompoundLiteral: 
          Typename: None, []
            ArrayDecl: []
              TypeDecl: None, []
                IdentifierType: ['int']
          InitList: 
            Constant: int, 0

When re-generating c code from this AST, I get the following
**void *ptr = int []0;**
which, obviously, doesn't compile.

**Comment by eliben** [comment]
This isn't a valid declaration in C. How would you expect the AST to look in this case? Does this code actually arise in practice for you?

**Comment by rachelhac** [comment]
I found this code line in this git projec <https://github.com/yongye/c>t that
I downloaded for testing purposes (See the Tetris_Game.c file, at the first
#define there).
I was also surprised it's a valid declaration and wasn't sure what it's
supposed to do.
After asking a few people, I assume it should initialize an array of length
1 with 0, then cast it to int[] and assign it to the void pointer.
The compiler understands it and the tetris game runs correctly so I guess
it is indeed a valid declaration.

2017-02-05 19:35 GMT+02:00 Eli Bendersky <notifications@github.com>:

**Comment by eliben** [comment]
The code in the link is different:

```
void* end_ptr = (int[]){0};
```

Note the star after the `void` - this *is* valid code. I think the parsing is correct since there's no cast here. The type in the `(...)` is compound initializer syntax. But the emission of C code back isn't great, and needs to be fixed.

**Comment by rachelhac** [comment]
Am I missing something?
I wrote you the line was *void* ptr = (int[ ]){0};*
Is that different in any way?

Anyway, many thanks for your great work :)



2017-02-06 15:10 GMT+02:00 Eli Bendersky <notifications@github.com>:

**Comment by eliben** [comment]
This is your original post on this issue: https://github.com/eliben/pycparser/issues/164#issue-205423036

... regardless, I agree that the C emission should be fixed here. I don't think it's a problem in the parsing side

**Comment by rachelhac** [comment]
Oh, sorry for the mistake!
Something went wrong there with the stars that make the text bold.

**Comment by kirbyfan64** [comment]
@rachelhac Always try surrounding code with backticks instead; GitHub will automatically format it `like this`.

**Comment by eliben** [comment]
Would you mind opening a new issue to describe the actual problem here with the C emission functionality? (AFAICS the parsing is done correctly)
