### ISSUE TITLE
Using pycparser as a submodule?

### ISSUE THREAD

**Issue by minexew** [eliben/pycparser#165]
This is more of a question than an issue --
I'm wondering if the scenario of using pycparser in another project as a git submodule (without installing anything) is "officialy" supported, or whether I should expect things to break with future versions.

In general, submodules are preferred to installed libraries, because they are self-contained and behave more consistently (for starters, you know exactly which version the user is going to get)

Thanks.

**Comment by kirbyfan64** [comment]
Not affiliated with this project, but is there a reason you can't just use virtualenv?

**Comment by eliben** [comment]
You can use any Python project as a Git submodule; with a submodule you lock a dependency to a certain revision hash so you always know what version you have. An alternative is to choose a specific version for pip requirements
