### ISSUE TITLE
Parsing C headers comments

### ISSUE THREAD

**Issue by adolia** [eliben/pycparser#167]
Hello!
Is it possible to parse C headers comments with pacparser?
Thanks in advance!

**Comment by eliben** [comment]
No, pycparser doesn't parse comments. It expect the C preprocessor to remove them before parsing

**Comment by adolia** [comment]
Thanks a lot for fast reply! Is it possible with some extension
implementation, because it has tokens for comments?
Can you, please, close an issue?

2017-02-15 18:19 GMT+02:00 Eli Bendersky <notifications@github.com>:
