### ISSUE TITLE
How general is pycparser?

### ISSUE THREAD

**Issue by rachelhac** [eliben/pycparser#173]
In a project I work on, I want to use pycparser to manipulate c code. The manipulation shouldn't change the functionality and compileabilty of the code.
I wish to build a tool that receives a c file and - using pycparser -  outputs a manipulated version of it. I want the tool to be very general and automatic an be able to work properly for as many c files as possible.

In one of the closed issues about conflict between the typedefs of the fake_libs and the real ones, someone asked:

So is it wrong to expect pycparser's output to be compileable, and running just as the initial c code?

And the answer was:

Yes, pycparser can lose information -- especially about the types. You can achieve full end-to-end transform and compile with some effort, but it's not something promised out of the box
-------
I'm now concerned that maybe pycparser is not general enough and therefore is not the good tool for my project. Can you please elaborate what information can be lost during c2c  process and what "effort" we should do to achieve full end-to-end transform?

Many thanks!

**Comment by eliben** [comment]
This is not a use case pycparser was specifically designed for. In general, compilation to AST loses syntactic information. But if you don't care about the emitted code looking as the original, that may be not very problematic. Also note that pycparser doesn't preprocess but expects preprocessed code, which will have all macros expanded, etc. So the code will look quite differently from the original code.

Moreover, when you use fake headers to parse types, these types are lost. The fake headers `typedef` all types to just `int`. If you want to avoid using fake headers, parsing your project becomes much more challenging if it depends on system headers that have a bunch of compiler-specific stuff pycparser doesn't support.

While I'm not saying it's impossible for small contained problems, I would expect using pycparser for this purpose would be quite challenging for "real life" C code bases. I would suggest using Clang's tooling library for this purpose -- https://clang.llvm.org/docs/LibTooling.html

**Comment by Syeberman** [comment]
pycparser tracks the source line numbers for each node in the AST (`coord`).  You could use pycparser to determine the changes you want to make, figure out what line they should be on, then read in the original source file and apply the changes.

This isn't something I've done myself, but I've been considering it for one of my projects.  It will only work if you're adding or removing whole lines: `coord` also tracks column information, but because this is after preprocessing the column will be incorrect on any line that uses a macro.

**Comment by rachelhac** [comment]
I don't care if the generated code doesn't look like the original one as long as the compilation works and the code is running as expected. So I'm not concerned about the preprocessing and other cosmetic changes.

Regarding the fake headers, the solution I found was to copy the original includes to the new code, then add to it the code generated from pycparser and remove all lines generated from the fake headers.
It's a little messy but so far it works fine.
Do you think it's enough or should I expect more problems?

**Comment by eliben** [comment]
It's hard to say - really depends on the specific use case. If you run into any troubles with pycparser, you can open Github issues.
