### ISSUE TITLE
Request for upgrading PLY to 3.10

### ISSUE THREAD

**Issue by plahoti** [eliben/pycparser#175]

**Comment by lorengordon** [comment]
I'd like to second this request. `ply` 3.9 does not work with a FIPS-enabled system, as `ply.yacc.signature()` relies on `md5`.

The signature function was rewritten in the `ply` 3.10 release and no longer seems to have this problem. This was breaking my attempt to install the `cryptography` library. I confirmed that the new version fixed the problem by replacing the vendored ply package in my local `pycparser` install with the files from the ply 3.10 release and was then able to install `cryptography`.

**Comment by plahoti** [comment]
Any idea as to when 2.18 is being planned?

**Comment by eliben** [comment]
@plahoti past experience shows that official pycparser releases are very painful due to the many dependent projects, so I try not to do this too often.
