### ISSUE TITLE
Can't handle blocks in case of swtich statement

### ISSUE THREAD

**Issue by heartbeast** [eliben/pycparser#186]
code like this：
`

    switch (n)
    {
    case 1: {
        int i = 0;
        LOG("%d",i);
        break;
    }
    ........
    }

`

**Comment by eliben** [comment]
It parses this file just fine:

```
int foo(int n) {
  switch (n)
  {
    case 1: {
        int i = 0;
        return i;
    }
    default: {
        return 2;
    }
  }
}
```
