### ISSUE TITLE
Release to remove MD5 requirement?

### ISSUE THREAD

**Issue by shaunbrady** [eliben/pycparser#196]
When install the Python module `cryptography`, the requirements of said package grab the latest released pycparser.  This does not include the recent commit of 3c0603d38ef46a4b7dc175420276abab35386c2f which removes the dependency on the MD5 hash function.

We're running a site that requires FIPS compliance, and unsafe cryptographic functions are disabled at a very low level (the kernel).  If we could get a release of pycparser, (at least to that commit), that would help us move on.  Manually installing the commit referenced above pacifies the failure observed when install `cryptography`.

Thanks!

SB

**Comment by eliben** [comment]
2.18 released

Please test and let me know if you run into any issues
