### ISSUE TITLE
Coords in preprocessed files instead of source?

### ISSUE THREAD

**Issue by alexdbooth** [eliben/pycparser#199]
I need to have the coords for function declarations in the preprocessed file as opposed to the source file so that I can wrap them in pragmas. Is this possible to do? Ideally inline functions would be included. 

Preprocessing, then editing source, then compiling from scratch is not an option due to size of the source.

**Comment by Syeberman** [comment]
If you remove the `#line` directives from the preprocessed file you'll get the coords inside the preprocessed file.  A quick `sed` command could accomplish this.

This would mean any downstream compiler steps would **also** report the preprocessed file coords, which probably isn't what you want.  If your preprocessor output is `file.i`, I would create a new `file.noline.i` with `#line` directives replaced with blank lines (so the line numbers stay the same).  Feed `file.noline.i` into pycparser, then use the output to modify `file.i`.

(Note, though, that if you're adding `#pragma`s to `file.i`, you're changing line offsets, meaning downstream compiler errors will report the wrong line number from the original.  You would need to ensure you only add `#pragma`s onto existing blank lines.)

**Comment by alexdbooth** [comment]
Thanks, @Syeberman! Removing those directives did the trick.
