### ISSUE TITLE
Parsing __attribute__ fails with latest version

### ISSUE THREAD

**Issue by brmmm3** [eliben/pycparser#201]
Trying following example fails with "pycparser.plyparser.ParseError: :3:32: before: __attribute__":

src = r"""
void testFunc(void) {
    extern int fooBarBuf[0x08] __attribute__ ((asection(".foo.bar","f=awB")));
} """

from pycparser import c_parser
p = c_parser.CParser()
ast = p.parse(src)
ast.show()

**Comment by eliben** [comment]
https://github.com/eliben/pycparser/wiki/FAQ#what-do-i-do-about-__attribute__

**Comment by aubertc** [comment]
The link was gobbled up in @eliben 's answer, it is actually

[https://github.com/eliben/pycparser/wiki/FAQ#what-do-i-do-about-\_\_attribute\_\_](https://github.com/eliben/pycparser/wiki/FAQ#what-do-i-do-about-__attribute__)
