### ISSUE TITLE
Support for register type xxx __asm__(yyy)

### ISSUE THREAD

**Issue by brmmm3** [eliben/pycparser#204]
Is it possible to add support for the following syntax:

register typeName variableName __asm__("registerName");

Best regards,
Martin

**Comment by eliben** [comment]
You can `#define` the `__asm__` away, as the FAQ suggests https://github.com/eliben/pycparser/wiki/FAQ

**Comment by brmmm3** [comment]
I know about this, but I don't want to define it away because I need it later.

**Comment by eliben** [comment]
pycparser doesn't support these, sorry. You can try https://github.com/inducer/pycparserext or Clang

**Comment by Madghostek** [comment]
> You can `#define` the `__asm__` away, as the FAQ suggests https://github.com/eliben/pycparser/wiki/FAQ

Sorry for digging up old issue! This shows up at the top of google search results, FAQ doesn't explain what exactly to do with `__asm__` so it might be confusing, here's quick way with `use_cpp`, might save somebody's time:

```py
AST = pycparser.parse_file(
                    path,
                    use_cpp=True, # this runs the preprocessor
                    cpp_args=[
                        "-D__asm__(...)=" # dots will eat the whole assembly block
                    ])
```

**Comment by eliben** [comment]
> > You can `#define` the `__asm__` away, as the FAQ suggests https://github.com/eliben/pycparser/wiki/FAQ
> 
> Sorry for digging up old issue! This shows up at the top of google search results, FAQ doesn't explain what exactly to do with `__asm__` so it might be confusing, here's quick way with `use_cpp`, might save somebody's time:
> 
> ```python
> AST = pycparser.parse_file(
>                     path,
>                     use_cpp=True, # this runs the preprocessor
>                     cpp_args=[
>                         "-D__asm__(...)=" # dots will eat the whole assembly block
>                     ])
> ```

Thanks. Feel free to send a PR for the FAQ if you'd like, I will be happy to incorporate it

**Comment by Madghostek** [comment]
> > > You can `#define` the `__asm__` away, as the FAQ suggests https://github.com/eliben/pycparser/wiki/FAQ
> > 
> > 
> > Sorry for digging up old issue! This shows up at the top of google search results, FAQ doesn't explain what exactly to do with `__asm__` so it might be confusing, here's quick way with `use_cpp`, might save somebody's time:
> > ```python
> > AST = pycparser.parse_file(
> >                     path,
> >                     use_cpp=True, # this runs the preprocessor
> >                     cpp_args=[
> >                         "-D__asm__(...)=" # dots will eat the whole assembly block
> >                     ])
> > ```
> 
> Thanks. Feel free to send a PR for the FAQ if you'd like, I will be happy to incorporate it

I think I was able to change the FAQ page without pr, since it's not part of the version control per se.
