### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by root9b** [eliben/pycparser#205]
https://i.imgur.com/hVCfdYz.png
in plyparser.py
Encountered while building pupy

**Comment by eliben** [comment]
See explanation in PR

**Comment by hugovk** [comment]
For anyone else ending up here after searching this error message, the PR is https://github.com/eliben/pycparser/pull/206, and the discussion is in https://github.com/eliben/pycparser/pull/198.

The conclusion is here: https://github.com/eliben/pycparser/pull/198#issuecomment-317001670.

In short, pycparser itself should not be used in `-OO` mode. 

In my case, don't set `PYTHONOPTIMIZE=2` globally on the CI, instead only for our own tests.
