### ISSUE TITLE
Mysterious 'At end of input' error

### ISSUE THREAD

**Issue by wisd0me** [eliben/pycparser#210]
I'm trying to parse headers on my project, and getting this strange error:
```
Traceback (most recent call last):
  File "./pycparse.py", line 30, in <module>
    cpp_path='cpp', cpp_args=cpp_opts)
  File "/usr/lib/python3.6/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/lib/python3.6/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/usr/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.6/site-packages/pycparser/c_parser.py", line 1763, in p_error
    self._parse_error('At end of input', self.clex.filename)
  File "/usr/lib/python3.6/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: common/include/ESR/ESRconfig/ESRconfig_defs_acls.h: At end of input
```
Any suggestions how can I debug it, and find out what's going on?
I tried pycparser 2.17 & 2.18 on python 3.6.1. Tried to google for that error, but found nothing similar.
Also, I'm using cpp:
```
    cpp_opts=[ "-Ifake_libc_include",
            "-D__attribute__(x)=",
            "-D__extension__(x)=", -Ixxx ]
```

While I was trying to parse my headers, I've noticed strange reaction on static inline functions in headers:
```
Traceback (most recent call last):
  File "./pycparse.py", line 30, in <module>
    cpp_path='cpp', cpp_args=cpp_opts)
  File "/usr/lib/python3.6/site-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/lib/python3.6/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/usr/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.6/site-packages/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/lib/python3.6/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: some_header.h:49:1: before: {
```
And I had to disable all such places in headers, after that I end up with this 'At end of input' error.

**Comment by wisd0me** [comment]
I've tried to use 'clang -E' instead of cpp, but still got the same error.

**Comment by eliben** [comment]
Can you submit a minimal example of a preprocessed file? Then I can try to run it through the parser and see how it goes? The file should be the output of `clang -E` so that no headers/preprocessing is needed.

**Comment by wisd0me** [comment]
It's hard for me to do a minimal file, cause I have no idea what exactly causing the error - I tried to parse smaller files with content similar to the one in which the errors happen - and it goes well. However, I've preprocessed the example file where both of the errors appear https://gist.github.com/wisd0me/5ced50495d4e4df806bb296a0fd2c809
To reproduce 'At end of input' error, remove the static inline function from it. Second error 'before: {' is reproduced as is.

**Comment by wisd0me** [comment]
I've finally found what exactly caused this error - there is __inline__ directive in one of dependency headers (not my code) with such comment:
```C
/* The gcc is compild with -ansi that is inline is not supported the __inline__ is gcc alternative */
```
I've changed it to inline, and got the ast

**Comment by wisd0me** [comment]
To resolve this, I think pycparser should support this alternative keywords https://gcc.gnu.org/onlinedocs/gcc/Alternate-Keywords.html#Alternate-Keywords
Or at least, if you don't want to cope with this gcc-specific stuff, there must be a recommendation in FAQ to define ```__inline__``` to ```inline``` and so on.
A clear error message about it will be __very__ useful as well.

**Comment by wisd0me** [comment]
I've created minimal example, to reproduce both of the above errors. It's just that:
```C

__inline__ int foo(void);

static inline int bar(int arg)
{
	return 0;
}
```
To get 'At end of input`, just remove the bar function. The link to my gist is updated either.

**Comment by wisd0me** [comment]
Also, If you're interested - I was able to parse headers, that use glibc, without fake includes. The final cpp command was this:
```
cpp -std=c99 \
     -D"__attribute__(x)=" \
     -D"__asm__(x)=" \
     -D__extension__= \
     -D__const=const \
     -D__inline__=inline \
     -D__inline=inline \
     -D__restrict= \
     -D__signed__=signed \
     -D__GNUC_VA_LIST \
     -D__gnuc_va_list=char \
     -Isomething_specific
```
The reason for not using fake includes is that I needed to know real types behind the typedefs, and fake includes does something else with them :-)
The software versions (might matter): Arch Linux x86_64, gcc 7.1.1, glibc 2.25

**Comment by eliben** [comment]
I wouldn't object to support alternative keywords -- feel free to send a PR

**Comment by wisd0me** [comment]
What about clear error message?
