### ISSUE TITLE
How to get end of a for loop, while in C file using the ast

### ISSUE THREAD

**Issue by DonAurelio** [eliben/pycparser#212]
**Is there a way to get the end of a  for, while nodes inside a function with the information given by the AST? or is there a way to calculate that value with the AST data?**

I saw this [article](https://stackoverflow.com/questions/36029091/pycparser-how-to-get-end-of-function-in-c-file
), but for functions I can calculate on which line each finishes. the problem is for other nodes.

**Comment by eliben** [comment]
When the node for `For` is [created in the parser](https://github.com/eliben/pycparser/blob/master/pycparser/c_parser.py#L1442), only the location of the `for` keyword is saved in the AST. 

You could perhaps get this data by hacking pycparser itself a bit (to save all relevant coordinates), but without changes I don't think it's possible

**Comment by DonAurelio** [comment]
Thanks I could solve my problem !!, the source code is easy to understand.
