### ISSUE TITLE
Allow comments in the AST

### ISSUE THREAD

**Issue by bdamm** [eliben/pycparser#217]
It's useful to have comments in the code in the AST, and, preprocessors have an option to include comments in the preprocessed output (e.g. clang -E --comments).  This is because my use of pycparser is to parse C code and produce documentation, where I want to take further actions on the comments.

Comments can be divided into LongComments and LineComments and considered Whitespace. A comparable implementation: https://github.com/pointlander/peg/blob/master/grammars/c/c.peg#L404

**Comment by Syeberman** [comment]
Hi @bdamm!  This question [has been asked before](https://github.com/eliben/pycparser/issues/124).

The short answer is that pycparser isn't designed to parse comments, instead assuming that the preprocessor has stripped them all out.  But see [this comment](https://github.com/eliben/pycparser/issues/124#issuecomment-253515820), where someone else was doing work to correlate comments with parsed code.

**Comment by bdamm** [comment]
Seems odd, why not just tokenize them along with everything else? Any one comment would be a single node in the AST. The boundaries of comments are easily added to grammar just as with any other grammar. There must be some complication.

It's very useful to treat comments are code if you're in the business of generating documentation from code.

**Comment by eliben** [comment]
@bdamm if you think this is easy, I encourage you to give it a shot :)
