### ISSUE TITLE
re-add main for _ast_gen.py

### ISSUE THREAD

**Issue by davidradernj** [eliben/pycparser#225]
When experimenting with changes to the AST, it was very helpful to have __main__ in _ast_gen.py to be able to quickly re-generate the c_ast.py.  Can you re-add?
If not, do you have a method for re-generating the ast other than just running the same code as in the main in interactive shell?

**Comment by eliben** [comment]
Take a look at `pycparser/_build_tables.py`

**Comment by davidradernj** [comment]
Thank you
