### ISSUE TITLE
Support __repr__ on nodes

### ISSUE THREAD

**Issue by ldore** [eliben/pycparser#226]
When creating parts of an AST from scratch, figuring out the actual types to use (as well as their correct constructor parameters), is currently a manual (and error-prone), process:
1. Create a source close to the intended code
2. Dump the AST, using `FileAST.show()`
3. Guess what types are needed, and refine until the correct structure is achieved.

Implementing [`__repr__`](https://docs.python.org/3/library/functions.html#repr) would definitely help, as step 3 would be a copy/paste of the `__repr__` output.

For example, using `tests_list_children`'s structure, `repr(comp)` could return:
```
Compound(block_items=[BinaryOp(op='+',
                               left=Constant(type='float',
                                             value='5.6'
                                             ),
                               right=Constant(type='char',
                                              value='t'
                                              )
                               ),
                      BinaryOp(op='-',
                               left=BinaryOp(op='+',
                                             left=Constant(type='float',
                                                           value='5.6'
                                                           ),
                                             right=Constant(type='char',
                                                            value='t'
                                                            )
                                             ),
                               right=Constant(type='char',
                                              value='t'
                                              )
                               ),
                      Constant(type='float',
                               value='5.6'
                               ),
                      Constant(type='char',
                               value='t'
                               )
                     ]
         )
```

**Comment by eliben** [comment]
I'm not sure I understand the problem you're describing. Have you tried the `attrnames` and `nodenames` parameters to `show` for more visibility?

**Comment by ldore** [comment]
Using `attrnames=True` and `nodenames=True` in `show` indeed gives more _visibility_.
As I often build (parts of an) AST manually (rewrites on massive C source base), this still leaves a lot of manual conversion to python code.
Part of the python doc for [`__repr__`](https://docs.python.org/3/library/functions.html#repr) states:
> ...  this function makes an attempt to return a string that would yield an object with the same value when passed to eval() ...

This is what I would like to achieve: A function that produces python code that can be copy/pasted to duplicate (parts of) the AST.

I rewrote and simplifed the `__repr__` implementation, so that it only relies on `__slots__`: changes to pycparser are now a lot smaller.

**Comment by eliben** [comment]
OK, I see. I've left a review on the PR.
