### ISSUE TITLE
Getting extended info about struct members

### ISSUE THREAD

**Issue by maximumspatium** [eliben/pycparser#230]
Hello crews,

first of all, thank you for bringing this amazing piece of software!

I'm currently working on improving various Python decompilation tools for binary executables (especially for embedded systems).
One of the important transformation passes is the rewriting of structure members in the form `somePtr->var40` to `somePtr->counter`. This greatly improves the readability of the output code.

Let's consider the following case:

- C headers with structure definitions are available
- `pycparser/examples/using_gcc_E_libc.py `is capable of parsing and displaying them

In order to implement the above described rewriting, I need to get member name and member size for specified struct offset. In other words, something like this is required:

```
name4offs(HWInfo, 40) --> 'cacheSize'
sizeof(HWInfo->cacheSize) --> 4
```

Alternatively, `name4offs` could be implemented by matching a precise offset against offsets returned by `offsetof(someStruct, someMember)`.

Is that currently possible with pycparser? If yes, I'd really appreciate some pointers!

Best regards
Max

**Comment by eliben** [comment]
Nope. pycparser is completely oblivious to the ABI. This should be doable with Clang - see https://eli.thegreenplace.net/2012/12/17/dumping-a-c-objects-memory-layout-with-clang for a starting point

**Comment by maximumspatium** [comment]
Thank you!
