### ISSUE TITLE
template decorator fails if no doc string is present

### ISSUE THREAD

**Issue by agroden** [eliben/pycparser#231]
**Problem:**
The function `_create_param_rules`, which is called within the `template` decorator, expects `__doc__` to be a string and calls replace on it. If no doc string is present, `__doc__` is `None`, and the function throws an `AttributeError`.

**Steps to reproduce:**
Apply the `template` decorator to any class that does not have a doc string.

**Proposed fix:**
Check for `None` before attempting to call replace.

**Comment by eliben** [comment]
This is discussed in length in #198. Why would this decorator be used on a function without a docstring?

**Comment by agroden** [comment]
Somehow I missed the discussion in [#198](https://github.com/eliben/pycparser/pull/198), my apologies. This has helped solve my issue. Thank you for the guidance!

**Comment by eliben** [comment]
No worries, #198 is closed already so it's not easy to discover. Happy it helped
