### ISSUE TITLE
Add parsing of pass-by-reference parameters

### ISSUE THREAD

**Issue by natezb** [eliben/pycparser#237]
I know this is a C++ feature, but the patch required is only 2 lines, so I thought I'd check.

I often encounter headers written for MSVC that are mostly C, with the occasional C++-ism. I usually do some preprocessing to normalize them before sending to pycparser, but this is pretty difficult to do for the pass-by-reference syntax without essentially writing a parser.

What I'd like to do is to simply interpret pass-by-reference as pass-by-pointer (e.g. parse `func(int &x);` as `func(int *x);`. This can be done by adding two lines to the `pointer` production so that it reads:

```
pointer : TIMES type_qualifier_list_opt
        | TIMES type_qualifier_list_opt pointer
        | AND type_qualifier_list_opt
        | AND type_qualifier_list_opt pointer
```

**Comment by eliben** [comment]
Have you considered extending pycparser the way https://github.com/inducer/pycparserext/tree/master/pycparserext does ?

**Comment by natezb** [comment]
Thanks for the suggestion, that sounds much more appealing to me than maintaining a patched version of pycparser.
