### ISSUE TITLE
Valueless enum members are generated incorrectly

### ISSUE THREAD

**Issue by natezb** [eliben/pycparser#240]
This seems to have been introduced by #216, which inadvertently removed some special-case checks. Enum members that don't have an assigned value now generate an invalid, empty assignment. For example:
```
typedef enum MOT_TravelModes
{
  MOT_TravelModeUndefined = ,
  MOT_Linear = 0x01,
  MOT_Rotational = 0x02
} MOT_TravelModes;
```
In the original code, `MOT_TravelModeUndefined` was assigned no value, and should be generated with no `=` sign.

**Comment by SethPoulsen** [comment]
I just realized the same problem.

**Comment by eliben** [comment]
@altendky PTAL

**Comment by SethPoulsen** [comment]
No need. I got it sorted out.

**Comment by saullocarvalho** [comment]
Is this still an issue? It seems like a commit has already fixed it.

**Comment by SethPoulsen** [comment]
Ya, I fixed it. It should be closed.

**Comment by natezb** [comment]
Just tested under 2.19, and works for me.
