### ISSUE TITLE
Generated code not compiling with typedef named struct defining multiple types

### ISSUE THREAD

**Issue by ldore** [eliben/pycparser#242]
When using a single `typedef struct` that defines multiple types, the parser converts the source to multiple single-type `typedef` nodes.
This causes problems when using a named `struct`.

For example:
```c
typedef struct MyStruct {
  int a;
} myType, *pMyType;
```
compiles correctly.

However, once parsed, and written back to C source, we get:
```c
typedef struct MyStruct {
  int a;
} myType;
typedef struct MyStruct {
  int a;
} *pMyType;
```
This does not compile, as `struct MyStruct` is defined twice.
```
error: redefinition of MyStruct
```

**Comment by eliben** [comment]
This seems to be the same issue as #195 ?

**Comment by ldore** [comment]
Yes, it is indeed a duplicate (though with a named `struct` this time).
I'll move the use case to #195.
