### ISSUE TITLE
AST manipulation (question)

### ISSUE THREAD

**Issue by rahul-iisc** [eliben/pycparser#244]
Hi,
I'm implementing functions for AST manipulation. With my limited exposure to both python and your library, I am finding it difficult to implement subtree insertion and deletion. I looked at the your rewrite AST example.

`assign = ast.ext[0].body.block_items[0]`
`assign.lvalue.name = "y"`
`assign.rvalue.value = 2`

This is easy when you know the exact position. But how to do it systematically? More specifically, lets say if I want to delete node number 8 (counted by preorder traversal), how do I do it?
I could get the path using a recursive solution to the node but the solution doesn't seem to be neat.
Any suggestions are welcome.

**Comment by eliben** [comment]
Using this library for advanced applications like AST manipulation requires some Python expertise. There's nothing different here from any other tree format that would be implemented in Python. You can delete list elements with `del`, and so on.
