### ISSUE TITLE
AST Mutator?

### ISSUE THREAD

**Issue by were** [eliben/pycparser#247]
I am writing some codes to manipulate the AST but I found there is no easy way to reform the AST structure dramatically (like injecting statements).

Shall I write some default AST Mutator so that it will be easier to manipulate the AST contents?

**Comment by eliben** [comment]
I wouldn't say it's hard to modify the AST, it being just a trivial Python structure with references and lists. 

I don't see much value in having sophisticated AST mutating APIs within pycparser, but feel free to implement it in a separate project
