### ISSUE TITLE
Incorrect Parsing of Floating Point Literals

### ISSUE THREAD

**Issue by SethPoulsen** [eliben/pycparser#253]
Currently, the floating point literal
```
double f = 4.5;
```
is parsed to 
```
Decl: f, [], [], []
  TypeDecl: f, []
    IdentifierType: ['double']
  Constant: float, 4.5
```
when really, the `type` attribute of the `Constant` node should be "double". Likewise, 
```
double f = 4.5L;
```
is parsed to 
```
Decl: f, [], [], []
  TypeDecl: f, []
    IdentifierType: ['double']
  Constant: float, 4.5L
```
when the `type` attribute of the `Constant` node should be "long double".  Note that the declared type is not what matters, it is the parsing of the floating point literal.

**Comment by eliben** [comment]
Good point! Feel free to submit a PR

**Comment by eliben** [comment]
Fixed by #277

**Comment by jam1garner** [comment]
Thanks for properly naming the commits/PR @robbert-harms, it made it much easier to find what caused my compiler to break upon installing on another machine (and therefore getting a new version of pycparser)!

**Comment by Sparika** [comment]
It seems that the case for `long int` is not handled either.
