### ISSUE TITLE
RuntimeError: Unable to invoke 'cpp'.  Make sure its path was passed correctly

### ISSUE THREAD

**Issue by eagleFromHeaven** [eliben/pycparser#256]
I recently install pycparser using pip install , when i tried this snipped:

`from pycparser import c_ast, parse_file
class FuncCallVisitor(c_ast.NodeVisitor):
    def visit_FuncCall(self, node):
        print("{} called at {}".format(node.name.name, node.name.coord))
ast = parse_file(r"C:\my_file_to_parse.c", use_cpp=True)`

i got this error:

`Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    ast = parse_file(r"C:\my_file_to_parse.c", use_cpp=True)
  File "C:\Python27\lib\site-packages\pycparser\__init__.py", line 86, in parse_file
    text = preprocess_file(filename, cpp_path, cpp_args)
  File "C:\Python27\lib\site-packages\pycparser\__init__.py", line 49, in preprocess_file
    ('Original error: %s' % e))
RuntimeError: Unable to invoke 'cpp'.  Make sure its path was passed correctly
Original error: [Error 2] The system cannot find the file specified`

what is that `cpp` file and from where i shuld get it???

**Comment by eliben** [comment]
Please refer to the README of the project and the other pages/posts it points to
