### ISSUE TITLE
Cast to struct as pointer

### ISSUE THREAD

**Issue by knieselpriem** [eliben/pycparser#257]
I tried to parse some C code with pycparser. Therefore I ran gcc with the option "-E" to preprocess the code. The result text shall be parsed with pycparser:
```
source_code = self._preProcess()
parser = c_parser.CParser()
ast = parser.parse(source_code, filename='<none>')
```
The following preprocessed C code is parsed well:
```
struct DB_MappingStruct
{ unsigned short ID;
  unsigned short ObsNr;
  unsigned short Index;
  unsigned char Typ;
  unsigned char SubIndex;
  unsigned short NovAdr;
};

typedef struct DB_MappingStruct DB_ObjectTyp;
...
extern DB_ObjectTyp *DB_CallingSignal;
...
unsigned int REQUEST_Check(DB_ObjectTyp *p);
```

... but these code fragments are raising the exception `pycparser.plyparser.ParseError: <none>:3119:32: before: *`:
```
unsigned int ((DB_ObjectTyp *) &DB_Object[214]);
...
if ((((DB_ObjectTyp *) &DB_Object[214]) = DB_Uint(E1_BP_SollRate)) == 0)
   {
   ...
```
I think it's a problem with the cast to the struct `DB_ObjectTyp` as pointer, because the `*` is interpreted as operator `t_TIMES` in "ctokens.py".

**Comment by eliben** [comment]
Can you provide a minimal example that can be fed into pycparser?

**Comment by eliben** [comment]
Not sure what you mean.

Can you minimize your input code so that it's minimal and still reproducing  the problem? No more than 10 lines of C input, if possible

**Comment by knieselpriem** [comment]
Sorry for the long pending answer.
I'm not allowed to give any C code example. Doesn't matter anymore. Meanwhile I used another tool.

I close the issue with status "won't fix" ;)
