### ISSUE TITLE
Install examples/* binary with pycparser package

### ISSUE THREAD

**Issue by marmeladema** [eliben/pycparser#258]
Hi,

I have a use case where i need to use the c_json binary example to convert c to json using pycparser.
But at the moment, examples are not installed so i have to use pycparser from the git source tree which is not very conveniant for the future users of my package.

I have forked this repository and made some changes for the examples to be installed and be more user friendly.

Would you be ok if i open some merge request ?

Thank you for reading me !

**Comment by eliben** [comment]
I prefer to keep it in the Git repository and keep the install process as minimal as possible
