### ISSUE TITLE
Function prototypes with pointer to pointer params

### ISSUE THREAD

**Issue by maximumspatium** [eliben/pycparser#259]
I'm trying to parse a real-world C source code (QEMU) with pycparser. It chokes on function prototypes containing pointer to pointer params like this:

```
typedef struct Error {
    int dummy;
} Error;
void func_with_pp_param(const char *, Error **);
```

Adding a name to the last param, i.e.

`void func_with_pp_param(const char *, Error **p);`

makes the parsing magically work.

Any chances to get a support for such constructs in pycparser?

**Comment by eliben** [comment]
Can you provide a minimal complete example that demonstrates an issue? The code you pasted is parsed find with the latest git revision of pycparser.

**Comment by maximumspatium** [comment]
> The code you pasted is parsed fine with the latest git revision of pycparser.

I confirm that the latest git revision of pycparser parses the above mentioned snippet correctly. The issue seems to come from pycparserext (see https://github.com/inducer/pycparserext/issues/36) so I'm going to ping there.
Sorry for the false alarm and thank you for the quick response.
