### ISSUE TITLE
pycparser + clang fail to parse pythread.h in python 3.7 - error: require native threads.

### ISSUE THREAD

**Issue by denfromufa** [eliben/pycparser#276]
Changes made to python 3.7 now cause failure of parsing in pythread.h by clang:

https://travis-ci.org/pythonnet/pythonnet/jobs/415741697#L1999

```
/opt/python/3.7.0/include/python3.7m/pythread.h:122:5: error: "Require native
      threads. See https://bugs.python.org/issue31370"
#   error "Require native threads. See https://bugs.python.org/issue31370"
```

Do I need to provide fake libc include for pythread.h or does this require some arguments to clang?

**Comment by eliben** [comment]
I'm not sure this is a bug for pycparser. I have no idea how `pythonnet` sets up its parsing of headers and what it does for fake includes, etc. It's possible that there's some `#define` missing here that leads `pythread.h` into the `#error` path.

**Comment by denfromufa** [comment]
@kijun yes, I followed @eliben suggestion about missing #define:

https://github.com/pythonnet/pythonnet/issues/609#issuecomment-413335193
