### ISSUE TITLE
Cannot apply to my own function type

### ISSUE THREAD

**Issue by MengLiew** [eliben/pycparser#278]
from __future__ import print_function
import sys
from pycparser import parse_file
from pycparser import c_parser

text = r"""
U1 funcOne(int a, int b){
    a = 1;
    b = 2;
    c = a + b;
    return c;

}
"""

parser = c_parser.CParser(text)
ast = parser.parse(text)
print("Structure 01:")
ast.show()

**Output: ParseError(':2:4: before: funcOne',)**

**Comment by eliben** [comment]
It has to know that `U1` is a type, so you need a `typedef` somewhere. See eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers

**Comment by MengLiew** [comment]
Hi Eliben, thanks for your reply. Is there any way I can ignore new types? I have a huge c file, it's hard to typedef all of them out.
