### ISSUE TITLE
version 2.19 broke compatibility with python 2.6

### ISSUE THREAD

**Issue by david-richer-adsk** [eliben/pycparser#281]
Hi guys,

We now get the following error when installing package that pull the latest (2.19) version of pycparser on python 2.6. 
```
File "/usr/lib/python2.6/site-packages/pycparser/__init__.py", line 14, in <module>
        from subprocess import check_output
    ImportError: cannot import name check_output
```

We know that python 2.6 is super old but it's still the version ship with CentOS 6. Feel free to drop support, a note about this in the change log would be appreciated. 

Thanks for your time,
David

**Comment by eliben** [comment]
Sorry for the breakage. I haven't been testing pycparser with Python 2.6 for year, and minimal 2.7 is noted in the README. I will put a note in CHANGES, in any case
