### ISSUE TITLE
Why pycparser can not parse multiple func call in one single line??

### ISSUE THREAD

**Issue by zmcrazy** [eliben/pycparser#285]
source code:
int func_call(int a, int b)
{
	return a + b;
}

int main()
{
	func_call(3, 4);
	printf("result is: %d\n", func_call(5,6));
}

When I use the pycparser example file 'func_calls.py' in pycparser-master\examples folder to test this source code:
![image](https://user-images.githubusercontent.com/31725114/47330326-67429000-d6aa-11e8-9d7d-0c3372d797ac.png)
But I only got one 'func_call' result. But from the source code we can find that there are to 'func_call' , one is 'func_call(3,4)', another is 'printf("result is: %d\n", func_call(5,6));'
Why it only shows only one result?? 
Result: 
clang  -E -ID:\Tools\pycparser-master\utils\fake_libc_include D:\py\ctest2.cpp
func_call called at D:\\py\\ctest2.cpp:30:2

**Comment by eliben** [comment]
That's an issue in the example. Thanks for noticing - it should be fixed now
