### ISSUE TITLE
ParseError in fake_typedefs

### ISSUE THREAD

**Issue by Xfel** [eliben/pycparser#286]
```
pycparser.plyparser.ParseError: [...]/python3.5/site-packages/autopxd/include/_fake_typedefs.h:151:9: Invalid declaration
```

The line in question is:
```
/* C99 stdbool.h bool type. _Bool is built-in in C99 */
typedef _Bool bool;
```

The likely cause for this is that our own headers use a custom define for the bool type instead of including stdbool.h. In general though, always including all the typedefs in _fake_typedefs.h creates this issue since they create unexpected typedefs.

**Comment by eliben** [comment]
The fake headers are not a core feature of pycparser - they are just there to help folks parse things without fighting headers too much. For custom setups you need a custom solution, so feel free to munge these headers to your liking
