### ISSUE TITLE
No wheels on PyPi

### ISSUE THREAD

**Issue by darkvertex** [eliben/pycparser#288]
Would be super nice if we had .whl (Python wheel) files in PyPi:
https://pypi.org/project/pycparser/#files

**Comment by webknjaz** [comment]
+1 I also expected pycparser to ship wheels.

FWIW there's a collection of wheels at https://www.piwheels.org/simple/pycparser/, it should be fine to reuse them on normal machines since they are universal.

**Comment by webknjaz** [comment]
@eliben?

**Comment by eliben** [comment]
I've had wheels for pycparser before, but they caused a bunch of version mismatch issues and I didn't have the time/energy to keep track (see https://github.com/eliben/pycparser/issues/148). pycparser is indirectly imported by a huge number of packages and everything setup-related is exceedingly sensitive to even tiny changes. Given that I don't have much time to spend on pycparser these days, I try to avoid setup changes as much as possible.

**Comment by webknjaz** [comment]
In this case, you'd need to ship OS-specific wheels and that's it. It's not that hard to do.

**Comment by filips123** [comment]
@eliben Why you don't create universal wheels for all OS? If this package is pure-Python, it should not be hard. Also, you can use Travis CI to do this on every release.

**Comment by graingert** [comment]
@eliben if you upload the sdist and bdist_wheel at the same time you wouldn't get a version conflict. The only reason #148 happend is the wheel appears to have been built from master rather than the tag that the sdist was built from
