### ISSUE TITLE
How do I reverse byte order of constants before printing? 

### ISSUE THREAD

**Issue by elgebalo** [eliben/pycparser#292]
Hello,
I am trying to figure out how to reverse the byte order of constants in C code before printing them. I initially tried to use the Constant class but I need the names of the constants too and the constant class only provides the value and type. My goal is to parse C code and be able to reverse the byte order of all constants (e.g 0x85A308D3 -> 0xD308A385) and also have the names of those constants. Do you have any ideas that would point me in the right direction? This is what I have so far...Appreciate any insight!

`from __future__ import print_function
import sys
sys.path.extend(['.', '..'])

from pycparser import c_parser, c_ast, parse_file

def show_tree(filename):
    ast = parse_file(filename, use_cpp=True,cpp_args=['-E', r'-Iutils/fake_libc_include'])
    ast_buffer_write=open("buffer.txt","w") # here will be your AST source
    ast.show(ast_buffer_write,attrnames=True)
    ast_buffer_write.close()
    
if __name__ == "__main__":
    if len(sys.argv) > 1:
        filename  = sys.argv[1]
    else:
        filename = 'xmrig-master/src/crypto/c_blake256.c'

    show_tree(filename)`

**Comment by eliben** [comment]
Names are there, but they are in parent/sibling nodes to the actual `Constant` node.

For example, the 2nd line in:
```
int main(int argc, char** argv) {
  int joe = 0xD305;
  return 0;
}
```
Will be parsed to something like:

```
      Decl: joe, [], [], []
        TypeDecl: joe, []
          IdentifierType: [u'int']
        Constant: int, 0xD305
```

So you can get to 'joe' by looking at the parent of the Constant node (see also https://github.com/eliben/pycparser/wiki/FAQ#why-dont-ast-nodes-in-pycparser-have-parent-links)

Constant nodes won't always have names though, so beware of that in the most general sense...

**Comment by elgebalo** [comment]
Thanks for the reply! Is it possible to modify node.value? I had a another related question...is it possible to modify node.value? Or do you need to use the Assignment class for that (lvalue/rvalue)?

**Comment by eliben** [comment]
It's possible to modify any AST nodes

**Comment by elgebalo** [comment]
Is that possible with NodeVisitor? it seems like modifying the AST would require ast.NodeTransformer, which I don't see anywhere.
