### ISSUE TITLE
How to analysis C source files in a big C project ??Using Clang to do preprocess.

### ISSUE THREAD

**Issue by zmcrazy** [eliben/pycparser#298]
![image](https://user-images.githubusercontent.com/31725114/49871218-94acee00-fe50-11e8-893a-58f472e1c153.png)
I mean some cpp args are included in makefile or else.
Need I extract them from makefile and write them in cpp_args of parse_file function in python scripts?

**Comment by eliben** [comment]
This blog post has some details/hints on analyzing large C projects:
https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/

**Comment by zmcrazy** [comment]
But in a large C project, there are many head file folders, and also many #define and #include  definition in Makefile ... ,but these files are not belongs to standard C. So, at this situation we can not use fake headers??Any other solutions ?

**Comment by eliben** [comment]
Header files that are part of the application have to be included by preprocessing. You have to observe the build flags, yes. The post I linked to has a practical example for Redis, though the details will be different for each application

**Comment by zmcrazy** [comment]
OK, thanks~, I have a C project with many makefiles, from what you said above, I think I need to analysis these makefiles to get all the Macro Definitions and Include Folders, right ? Is there any tools to do this ?e.g.,  extract the makefile...

**Comment by eliben** [comment]
Some options are discussed in https://eli.thegreenplace.net/2014/05/21/compilation-databases-for-clang-based-tools

That post is about Clang tooling, but it's the same need - extracting build flags so that analysis tools can run
