### ISSUE TITLE
Included ply CPP preprocessor does not handle #if a != b correctly 

### ISSUE THREAD

**Issue by rreilink** [eliben/pycparser#299]
pycparser.ply.cpp.Preprocessor.evalexpr does an attempt to convern a C-expression to a Python expression by converting ! to not (as in: `!(a==b)`) but inatvertendly it also convert `a!=b` to `a not =b` which is obviously not valid syntax.

Furthermore, undefined identifiers are replaced by `0L` which is not valid Python3 syntax, this should be just `0`.

Additionally, the preprocessing of the evaluation and the actual evaluation should be split into separate methods, such that when deriving from this class, the evaluation could be overridden while the preprocessing (macro expansion etc) stays as-is (in case e.g. due to security concerns one might not want to use eval)

I will prepare a PR.

**Comment by eliben** [comment]
The ply/ dir is just a fork (vendoring) of the https://github.com/dabeaz/ply project, so all issues with its contents should be raised with the project.

Besides, pycparser itself doesn't use ply's cpp.py for anything.

**Comment by rreilink** [comment]
> The ply/ dir is just a fork (vendoring) of the https://github.com/dabeaz/ply project, so all issues with its contents should be raised with the project.
> 
> Besides, pycparser itself doesn't use ply's cpp.py for anything.
@eliben 

1. If these fixes would be included into the dabeaz/ply project, would you be willing to pull them into pycparser? If not, it won't make sense for me to make the effort to do so.

2. Would you be interested in a PR that *does* allow ply's cpp to be used? (i.e. facilitates using plys cpp with pycparser). I have found it more convenient than using the system's cpp e.g. on Windows where cpp is not always available, or when a different cpp version may result in a different result.

**Comment by eliben** [comment]
I occasionally upgrade the PLY version inside pycparser, usually with official releases of PLY.
Note that PLY's cpp is very incomplete, according to its author - I would suggest checking with them for more details. pycparser tries to remain cpp-agnostic on purpose, in order to avoid all this complexity in the project
