### ISSUE TITLE
Included ply CPP preprocessor does not read files with non-ascii characters

### ISSUE THREAD

**Issue by rreilink** [eliben/pycparser#300]
In pycparser.ply.cpp.Preprocessor.include, files are opened as text using unspecified encoding, which result in using `locale.getpreferredencoding(False)`. Using a locale-dependent setting to parse source code is not a good thing. I think a safe default would be to use utf-8 with surrogate escape error handling, which allows all encodings to be decoded without data loss. GCC also uses utf-8 by default.

To provide more flexibility for the user, the reading of the included file could be done in a separate method, allowing the user of the class to override this specific part in a derived class (e.g. to substitute constant text for system include files)

I will prepare a PR.

**Comment by eliben** [comment]
See answer in #299
