### ISSUE TITLE
I have the same issue exactly,

### ISSUE THREAD

**Issue by Aishaaldosery** [eliben/pycparser#306]
I have the same issue exactly, 

ast = parse_file(filename, use_cpp=True,
                     cpp_path='clang', 
                     cpp_args=['-E', r'-Iutils/fake_libc_include'])

and the parse_file function looks exactly as you post (I didn't change anything ), I use gcc -E for preprocess

_Originally posted by @Aishaaldosery in https://github.com/eliben/pycparser/issues/252#issuecomment-462096066_

**Comment by eliben** [comment]
Please read http://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/
