### ISSUE TITLE
Generating array type

### ISSUE THREAD

**Issue by amirgon** [eliben/pycparser#312]
Consider the following:

```python
from pycparser import c_parser, c_ast, c_generator
parser = c_parser.CParser()
gen = c_generator.CGenerator()

ast = parser.parse("int x[17];")
gen.visit(ast.ext[0])
gen.visit(ast.ext[0].type)
```

Now, `gen.visit(ast.ext[0])` returns the expected result: `'int x[17]'`.
**However, `gen.visit(ast.ext[0].type)` returns: `'int17'`**

I would expect `gen.visit(ast.ext[0].type)` to return `'int[17]'`.  
Returning `'int17'` (the concatenation of `'int'` and `'17'`) just doesn't make sense.  

Trying to figure this out, I looked for `dim` on `c_generator.py` but the [only place it appears](https://github.com/eliben/pycparser/blob/992715f12aef69eb1351308f14fb5f1ff972ce57/pycparser/c_generator.py#L385) handles the concatenation of the square brackets as well, so I'm not sure where the `int17` could come from.

Any idea?

**Comment by eliben** [comment]
I believe this is because `ast.ext[0].type` is an `ArrayDecl`, not a `TypeDecl`. Follow the logic in the `_generate_type` method of the C generator.

Patches welcome!

**Comment by amirgon** [comment]
> Patches welcome!

@eliben #313

**Comment by amirgon** [comment]
Thanks.
