### ISSUE TITLE
Getting Define errors in STD Libraries

### ISSUE THREAD

**Issue by BollimpalliSuryateja** [eliben/pycparser#334]
There are lot of Define errors poping up is there a simpler way to solve this than Writing Define for each of the error like (-D'__nptr=' -D'__endptr=')

pycparser.plyparser.ParseError: /repo/ebolsur/int-g2/build/devfs/bpu/rcs-distro/arm/usr/include/stdlib.h:165:27: before: __endptr
 /repo/ebolsur/int-g2/build/devfs/bpu/rcs-distro/arm/usr/include/stdlib.h:164:46: before: __nptr
 /repo/ebolsur/int-g2/build/devfs/bpu/rcs-distro/arm/usr/include/stdlib.h:71:19: before: __attribute__
pycparser.plyparser.ParseError: /repo/ebolsur/int-g2/build/devfs/bpu/rcs-distro/arm/usr/include/sys/select.h:106:51: before: __readfds

**Comment by BollimpalliSuryateja** [comment]
this error happens when the preprocessed file is fed to parser.

>>> pycparser.parse_file('/repo/surya/sm/port_sm.c.pp')

and the preprocessed file is generated from make file using armgcc.

**Comment by eliben** [comment]
Please provide a minimal reproducer.

And make sure you read the FAQ -- https://github.com/eliben/pycparser/wiki/FAQ and also https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/
