### ISSUE TITLE
Problem with function pointer

### ISSUE THREAD

**Issue by BollimpalliSuryateja** [eliben/pycparser#335]
static sm_trans transition_table[NUM_STATES][NUM_EVENTS] = {

        [NA] =
        {
                [CFG_DONE] =
                {
                        .cng = DOWN,
                        .action = drop_down
                }
        },

        [L2UP] =
        {
                [READY] =
                {
                        .action = subscribe
                },
                [RESERVED] =
                {
                        .action = remove_endpoints
                },
                [DOWN] =
                {
                        .cng = DOWN
                },
                [IP_READY] =
                {
                        .cng = UP
                },
        },
};

static sm_trans *transition_lp(int state, int trigger)
{ /////errror before this brace
        return &transition_table[state][trigger];
}

**********************************************error********************************************
pycparser.plyparser.ParseError: home/sm.c:170:1: before: {

**Comment by eliben** [comment]
Please provide a complete, minimal reproducer

**Comment by BollimpalliSuryateja** [comment]
Will parser work for this logic 

typedef  sm_trans *transition(int,int)

static sm_trans *transition_lp(int state, int trigger)
{
return &function1_table[state][trigger];
}

**Comment by eliben** [comment]
This doesn't look like valid C to me, so the answer is no.
