### ISSUE TITLE
C parser doesn't work with function attribute to place function in special sections

### ISSUE THREAD

**Issue by thekenu** [eliben/pycparser#336]
If I add to `__attribute__ ((section ("bar")))` to my function prototype and then run `c-to-c.py`, the program breaks and is unable to print out anything.

**Comment by refi64** [comment]
https://github.com/eliben/pycparser/wiki/FAQ#does-pycparser-support-gnuvisual-c-extensions

**Comment by thekenu** [comment]
Thank you!
