### ISSUE TITLE
DeprecationWarnings emitted from re.compile

### ISSUE THREAD

**Issue by mattip** [eliben/pycparser#349]
Running `python3.6 -mpytest tests` raises a DeprecationWarning
```
tests/test_c_lexer.py:166
  /tmp/pycparser/tests/test_c_lexer.py:166: DeprecationWarning: invalid escape sequence \9
    '"jx\9"',

tests/test_c_lexer.py:169
  /tmp/pycparser/tests/test_c_lexer.py:169: DeprecationWarning: invalid escape sequence \9
    '"fo\9999999"',

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

It seems all the `re.compile` expressions should be using `r` raw strings?

xref numpy/numpy#14554

**Comment by eliben** [comment]
Thanks for the report. I'll accept PRs to fix this

**Comment by eliben** [comment]
I'm starting to plan for releasing a new version -- see #365 

If you want this fix in, hurry up :-) I actually can't reproduce the warning, perhaps because I'm not using pytest.
