### ISSUE TITLE
Issue when running example codes

### ISSUE THREAD

**Issue by Aiswarya-kk** [eliben/pycparser#351]
Error when trying this command :
**python examples/c-to-c.py /home/aishu/Desktop/coll_rew_ast.txt**
![ast-c-error](https://user-images.githubusercontent.com/53484324/65525506-3b103e80-df0d-11e9-9bc7-3022625f8459.png)

**Comment by kkoomen** [comment]
Getting same errors as well and no example is working for me.

**Comment by eliben** [comment]
Could you please provide a minimal reproducer?
