### ISSUE TITLE
Avoid __file__

### ISSUE THREAD

**Issue by jayvdb** [eliben/pycparser#355]
`pycparser` and thus `cffi` are failing in PyOxidizer because `pycparser.ply.lex` is expecting `pycparser.c_lexer` and `pycparser.c_parser` to have a `__file__`

```py
cffi.api:112: in cdef
    ???
cffi.api:126: in _cdef
    ???
cffi.cparser:358: in parse
    ???
cffi.cparser:363: in _internal_parse
    ???
cffi.cparser:305: in _parse
    ???
cffi.cparser:52: in _get_parser
    ???
pycparser.c_parser:88: in __init__
    ???
pycparser.c_lexer:66: in build
    ???
pycparser.ply.lex:894: in lex
    ???
E   AttributeError: module 'pycparser.c_lexer' has no attribute '__file__'
```

I can populate those `__file__` with `'junk'` and it seems that my build gets a _lot_ further, so possible those values are not needed.  Or there could be a fallback, such as using `importlib.resources`.

**Comment by eliben** [comment]
`pycparser.ply.lex` is a dependency from https://github.com/dabeaz/ply
