### ISSUE TITLE
add helper for replacing a node, i.e. replace(parent_node, old_node, new_node)

### ISSUE THREAD

**Issue by robertmuth** [eliben/pycparser#356]
I am not sure if pycparser is meant mostly for read-only access to the AST or if modifications are 
"in scope". In the latter case a helper  for updating nodes would be useful.
Concretely, something like this:

https://github.com/robertmuth/Cwerg/blob/034b6c9f135f39847b8957455e256d22175a6ad3/common.py#L171

Hopefully, there is some introspection magic that would make this less verbose and error prone.

**Comment by eliben** [comment]
Indeed, the main goal of pycparser is for analyzing the AST, not for changing it. It should be possible to modify the AST, of course, but this functionality is out of scope.

**Comment by brunoappentra** [comment]
@eliben I guess my question is related to this thread... how hard would it be to accomplish this simple task posted in SO [https://stackoverflow.com/questions/60195762/how-to-remove-ast-nodes-with-pycparser](https://stackoverflow.com/questions/60195762/how-to-remove-ast-nodes-with-pycparser)?

For my particular use-case (static analysis tools) I was going to use [c-reduce](https://embed.cs.utah.edu/creduce/) to reduce the complexity of complex c codes but then I thought maybe pycparser would acomplish the goal much easily.

Thanks in advance.

**Comment by eliben** [comment]
@brunoappentra it wouldn't be hard. ASTs are just Python data structures you can modify at will.

I'm going to close this issue as out of scope; please open new issues for new problems, if needed.
