### ISSUE TITLE
Running pycparser on entire project repositories

### ISSUE THREAD

**Issue by shubhamrsangle** [eliben/pycparser#361]
I needed to use pycparser project so I went through this blog https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers

By, going through this, I realized that it's very tough to run this project on some big project, which I actually need too do. As in blog you showed that we need to tackle every header problem one by one and we are knowing about what to include in this pre-processing command  after getting error one by one

gcc -nostdinc -E -D'__attribute__(x)=' -Iredis/src \
                   -Ipycparser/utils/fake_libc_include \
                   -Iredis/deps/lua/src redis/src/redis.c > redis_pp.c

Can you help me by giving some script or pointing me to some script if I want to run it on  every file of some repository as we can't pre-process every file one by one.

**Comment by eliben** [comment]
No, there's no magic solution. You have to do it the way the blog post described. Typical projects using pycparser apply it to a small number of code-bases, so this is just a one time "start up cost" that gets amortized over the lifetime of the project.

It's not clear to me what you mean by "can't pre-process every file one by one". The compiler compiles a project "every file one by one", so pycparser would need to analyze each project in the same way.
