### ISSUE TITLE
Running Pycparser on entire repository

### ISSUE THREAD

**Issue by shubhamrsangle** [eliben/pycparser#367]
No, there's no magic solution. You have to do it the way the blog post described. Typical projects using pycparser apply it to a small number of code-bases, so this is just a one time "start up cost" that gets amortized over the lifetime of the project.

It's not clear to me what you mean by "can't pre-process every file one by one". The compiler compiles a project "every file one by one", so pycparser would need to analyze each project in the same way.

_Originally posted by @eliben in https://github.com/eliben/pycparser/issues/361#issuecomment-581904058_

I don't need any magic solution, just need to know that can this be automated by script or have to do everything manually? By "can't pre-process every file one by one", I mean that I can't do it manually for every file in repository. There will be thousands of file in project, how can I do it manually for every file?

**Comment by eliben** [comment]
Please post the comment on the original issue - there's no need for a separate one. You should be still able to post comments on a closed issue, and I will be notified. If you feel you're not getting a response to a closed issue you could reopen it.

I don't have a script to point you to, but once you've manually worked through a small number of files in your repo you can usually use the same build flags + headers to process *all* files in the repo. New problems will come up once in a while but overall it shouldn't be too much.
