### ISSUE TITLE
Windows: utils/* not being installed?

### ISSUE THREAD

**Issue by paniq** [eliben/pycparser#37]
I noticed that cpp.exe is not installed with pycparser. Is that a bug or a deliberate choice? It would be enormously helpful to be able to depend on cpp.exe when pycparser is installed as in e.g. 

`CPPPATH = os.path.join(os.path.abspath(os.path.dirname(pycparser.__file__)),'utils', 'cpp.exe')`

**Comment by kugel-** [comment]
I've too noticed that utils/* is not installed with setup.py. This results in the Arch Linux package lacking the fake libc headers. I guess without them pycparser is greatly limited.

**Comment by Mause** [comment]
`utils/` inclusion should have been fixed with ada0c04b7f5a327fa8c826f271fe40c2a6852f7b (see #96), but a release hasn't been done since unfortunately

**Comment by outcast** [comment]
This doesn't seem to have repaired the issue on virtual env on os x

**Comment by outcast** [comment]
it only works when you execute setup.py sdist. I would have expected to work with the install command as well

**Comment by eliben** [comment]
Utils is not installed, see #224 

I don't plan to fix this, but a notice has been added to the README
