### ISSUE TITLE
i wanna convert ast to cfg, but i have no idea,cause im not a coumputer professional student, can you give me some adivce?

### ISSUE THREAD

**Issue by leslielee619** [eliben/pycparser#370]
hello dear friend,
im major in mechinesm, but you know that  you could select courses no matter which college you are in, so i select a class which name <Software source code analysis> ， just cause i ever used pyqt5, so im happy to take a class ,and feel sad when the teacher give us a Semester assignment.
he want us to analysis a c code and get the cfg and du path.
im major in mechinsm, and im familiar with my profeesinal courses and python，but i don know about compilation principle.
so i try to find how to solve my assignment in github , in stackflow and so on. i find  your package could generate an ast.
and now i want to convert it to cfg, so i want get your views about this.

**Comment by eliben** [comment]
Without being somewhat familiar with compilers it will be difficult for you to generate a CFG using pycparser. If you really want to do this I suggest reading a book on compilers or going through some deep tutorials.
