### ISSUE TITLE
feat: support code snippet

### ISSUE THREAD

**Issue by yxliang01** [eliben/pycparser#373]
Would be nice if pycparser can support parsing C code snippet. For example, the following is a valid C code snippet but pycparser cannot parse as it only supports parsing file-level C code (as far as I think).

```c
if (1) {}
```

The example above cannot be parsed by pycparser 2.20 .

**Comment by eliben** [comment]
This should be trivial to implement by wrapping it in a dummy void function:

```
void __f() {

  YOUR CODE HERE

}
```

And then stripping away the function definition AST node.

**Comment by yxliang01** [comment]
Thanks @eliben for your quick comment. Yes, this is doable. But, at first place, I find it a bit weird to have such limitation though. I don't really know the internals of this codebase, but built-in support would be better I feel. This can arguably boost the application of pycparser. Just my two cents.
