### ISSUE TITLE
Replace assertions with checks that raise `ParseError`s

### ISSUE THREAD

**Issue by huzecong** [eliben/pycparser#378]
https://github.com/eliben/pycparser/blob/61eac63fda12f9ba4504def70d0d76cd3ac1bbff/pycparser/c_parser.py#L464-L467

In this and other lines of `c_parser.py`, assertions are used to verify that said condition is true. However, there can be input that will result in the condition being false. For example, the following code triggers an `AssertionError` at the line above:
```c
typedef struct __attribute__((packed)) {
    char name[36];
    int attr;
} foo;
```
I would argue that the desired behavior here is to be consistent and throw a `ParseError` instead.

**Comment by eliben** [comment]
Feel free to send PRs for concrete cases. Let's start with one and see how it goes from there

**Comment by huzecong** [comment]
A PR for this issue sounds simple enough; I'll try to create one tomorrow.
