### ISSUE TITLE
AttributeError: 'Constant' object has no attribute 'name'

### ISSUE THREAD

**Issue by timur-tabi** [eliben/pycparser#382]
I've written a test script that's almost identical to func_defs.py, but when I run it, I get this error:

  File "/home/ttabi/sw/pvt/ttabi/boardobj.py", line 29, in visit_FuncCall
    if node.name.name == self.funcname:
AttributeError: 'Constant' object has no attribute 'name'

I just copied visit_FuncCall verbatim.  I think the API has changed since this example was written, but I don't know Python well enough to debug this.

**Comment by eliben** [comment]
I suppose you're talking about `func_calls.py`. It runs fine for me. What happens if you run the actual example, not a modified one?

**Comment by timur-tabi** [comment]
The example itself works fine.  I guess there's just something wrong with my code.  I'll have to use something other than pycparser for my project.
