### ISSUE TITLE
Parse failed with Comment and UnicodeDecodeError

### ISSUE THREAD

**Issue by tiantian1645** [eliben/pycparser#384]
I found i could not set encoding in parse_file which cause UnicodeDecodeError

Use this remove comment  https://stackoverflow.com/a/2319116
```python
def removeComments(string):
    string = re.sub(re.compile("/\*.*?\*/",re.DOTALL ) ,"" ,string) # remove all occurrences streamed comments (/*COMMENT */) from string
    string = re.sub(re.compile("//.*?\n" ) ,"" ,string) # remove all occurrence single-line comments (//COMMENT\n ) from string
    return string
```

**Comment by eliben** [comment]
It would really help if you could provide more details, please. I'm not sure how this `removeComments` function relates to pycparser at all.

**Comment by bwoodsend** [comment]
I have some code which can strip comments from C source. It's slightly more involved than the `removeComents()` function showed above (which would break if either `//` or `/**/` is part of a literal). I'd like to slot it into `pycparser` as an alternative to using `gcc -E` to preprocess away comments. Would you accept a PR with this change?

**Comment by eliben** [comment]
`gcc -E` does much more than preprocess away comments.

Sorry, I'm not inclined to accept a preprocessor into pycparser at this stage.

**Comment by bwoodsend** [comment]
> `gcc -E` does much more than preprocess away comments.

Actually on running pycparser on my comment stripped source code I see that comments are just the tip of the iceberg. In which case such a feature would be useless. Fair enough then. Perhaps you should close this issue - I believe that was the original intention of this issue,
