### ISSUE TITLE
Exponential time complexity when generating code from AST with nested `sizeof`s.

### ISSUE THREAD

**Issue by huzecong** [eliben/pycparser#385]
Minimum example to reproduce:
```python
from pycparser.c_parser import CParser
from pycparser.c_generator import CGenerator

# Code is 30 nested `sizeof`s.
code = "int x = sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(sizeof(int))))))))))))))))))))))))))))));"
tree = CParser().parse(code)
print(tree)  # the tree is correct
print(CGenerator().visit(tree))  # this never stops
```

The issue is within `CGenerator.visit_UnaryOp`:
https://github.com/eliben/pycparser/blob/61eac63fda12f9ba4504def70d0d76cd3ac1bbff/pycparser/c_generator.py#L61-L72
In the case where `n.op` is `sizeof`, `n.expr` is visited twice. When there are nested `sizeof`s, the leaf nodes will be visited an exponential number of times. (Although in reality such code wouldn't make sense)

I can create a PR with a few of my previous issues, but it might take a few days before I can work on this.

**Comment by eliben** [comment]
Interesting find. Feel free to send a PR to fix this.
