### ISSUE TITLE
How to get functions but not in structs?

### ISSUE THREAD

**Issue by thoni56** [eliben/pycparser#388]
I want to find function definitions/declarations but avoid anything that is not a "top level" function, including struct fields that are pointers to functions:

    struct {
        void (*func)();
    };

A straight forward approach with `FuncDefVisitor()` does not work since it is impossible to see if the visited node is inside a struct.

Looping over all nodes on top level feels like re-implementing the visiting dispatch logic.

Is there an easier way?

**Comment by eliben** [comment]
There's not much logic to re-implement, really. Just scan the top-level decls looking for the node type you're interested in?

**Comment by thoni56** [comment]
Aaah, yeah, obviously. I was thinking the "backwards" declaration structure of C would make it more complicated, having to look down the Ast to see if this declaration was a function. But obviously the top level would be a FuncDef it is a function, duh!

Thanks.
