### ISSUE TITLE
Full source code?

### ISSUE THREAD

**Issue by sleirsgoevy** [eliben/pycparser#396]
Although the code is kinda open source, most of it seems to be autogenerated by `yacc`, and therefore is not "source code", as per the FSF definition. Is it possible to see the real source of it?

**Comment by refi64** [comment]
This project doesn't use yacc...

**Comment by eliben** [comment]
While pycparser uses `ply` for generating a lexer and parser, none of the code committed into the GitHub repository is auto-generated with these tools. The tools auto-generate code when pycparser is first run (the generated tables are packaged into the release tarballs/wheels, for optimization). All the code of pycparser is open source with a BSD license and available in this GitHub repository.
