### ISSUE TITLE
Open to single-line comment removal?

### ISSUE THREAD

**Issue by samyk** [eliben/pycparser#402]
Hi! Thanks for the great project.

I found that unlike GNU's `cpp`, Apple's `cpp` (clang on macOS) does not replace single-line comments (`//`) using any of the C-language standards, though it does do this for C++ (`cpp -xc++`).

I found some of the previous issues (#102, #217) regarding comments and understand supporting them in the AST would be complicated as they can appear almost anywhere according to C99's 6.4.9 "Comments" section, but I'm curious if either one of the following options would be acceptable to allow pycparser to work more cleanly out of the box across platforms:

1. Preprocess single-line comments, defined in C99 6.4.9 (2), replacing them with a single space, as defined in C99 5.1.1 (2)(3), and _not_ include them in the AST
2. Adjust `parse_file`'s and `preprocess_file`'s default argument of `cpp_args` from `''` to `'-xc++'`, however I don't know if there are C++-specific caveats or other preprocessors that will break if this is enabled by default.

I'm specifically using:
```
tigerblood:/Users/samy/p$ cpp --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I'm happy to submit a PR if so.

Thanks!

**Comment by eliben** [comment]
Thanks for the detailed report.

This kind of cross-plaform difference makes me more determined to avoid any preprocessor concerns in pycparser, if anything :-)

As discussed earlier, preprocessing *some* aspects and not others in pycparser just doesn't seem to be worth the cost. As for `parse_file`, etc. - it takes arguments for a reason -- why should it have platform-specific defaults?

Closing this, but if you have any new information here - feel free to reopen.

**Comment by samyk** [comment]
To answer your question, the default I'm suggesting is not platform-specific but seems to be more platform-agnostic. The way it works today, pycparser only works with GNU cpp out of the box when there are single-line comments in the code and breaks on macOS (if there are other specific compilers please let me know and I'll be happy to test the portability) but by adjusting the default argument, it will work out of the box on both GNU cpp and Apple clang, increasing the platform support.

I completely understand your desire to not support some pre-processing steps and not others, however I don't think we can consider comments only as a pre-processing step. Note that gcc, clang, and arm-none-eabi-gcc all support single-line comments _post-preprocessing_.

This can be tested on gcc by compiling a `.i` file with the -S flag which bypasses the preprocessor and only performs compilation. If an `#include` is in there, it breaks as there's no preprocessing, but comments are handled, thus all compilers I've tested are handling comments where pycparser differs.
