### ISSUE TITLE
AST Plot

### ISSUE THREAD

**Issue by brunaostii** [eliben/pycparser#406]
Hi, is there a way to plot the ast tree?

**Comment by eliben** [comment]
I'm not entirely sure what you mean by "plot" in this context. You can dump the AST to text (see the `dump_ast.py` example), but nothing in terms of graphics. It should be possible (and not too hard) to dump an AST into DOT format (for Graphviz), but there's no code for this in the pycparser repo at this time.

**Comment by brunaostii** [comment]
Thank you, I'll try this lib :D
