### ISSUE TITLE
Implicit/Omitted Type Error

### ISSUE THREAD

**Issue by 3ddiddE** [eliben/pycparser#407]
First of all, thank you very much for this parser! It is really useful.

I am working on a project that has to create C code that violates best practices/guideline rules (e.g. MISRA).
One of the rules states that types have to explicitly be specified.
E.g. this is my example code, that should be emitted by the c parser:

>static a = 0;

GNU GCC has no problems compiling this code via `gcc -std=c99` (with Wimplicit-int warning).
pycparser is raising this exception:
>Traceback (most recent call last):
>  File "/tmp/test/./test.py", line 10, in <module>
>    ast = parser.parse(text)
>  File "/usr/lib/python3.9/site-packages/pycparser/c_parser.py", line 149, in parse
>    return self.cparser.parse(
>  File "/usr/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 331, in parse
>    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
>  File "/usr/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 1118, in parseopt_notrack
>    p.callable(pslice)
>  File "/usr/lib/python3.9/site-packages/pycparser/c_parser.py", line 718, in p_decl_body
>    decls = self._build_declarations(
>  File "/usr/lib/python3.9/site-packages/pycparser/c_parser.py", line 449, in _build_declarations
>    fixed_decl = self._fix_decl_name_type(declaration, spec['type'])
>  File "/usr/lib/python3.9/site-packages/pycparser/c_parser.py", line 337, in _fix_decl_name_type
>    self._parse_error(
>  File "/usr/lib/python3.9/site-packages/pycparser/plyparser.py", line 67, in _parse_error
>    raise ParseError("%s: %s" % (coord, msg))
>pycparser.plyparser.ParseError: :2:8: Missing type in declaration

using this minimal example:
>#!/usr/bin/env python
>from pycparser import c_parser
>
>text = r"""
>static a = 0;
>"""
>
>if __name__ == '__main__':
>    parser = c_parser.CParser()
>    ast = parser.parse(text)

Is there any chance that this will be fixed?
Although this is preventing correct code to be parsed (reading the file above)

**Comment by eliben** [comment]
I believe this code isn't really ISO C99. If you compile with `-pedantic-errors` you'll get an error.

pycparser is solely focused on strict ISO C99, it doesn't try to be permissive like other compilers.
