### ISSUE TITLE
why this "#error" raise errors ?

### ISSUE THREAD

**Issue by Arfaoui-Mahdi** [eliben/pycparser#412]
I have C files to parse, and in one of them, I have some code that should be compiled with GHS, 

```
#ifdef __ghs__

/* Allocate initialized static variables in default/SRL section */
#pragma ghs section data=default
#ifdef __ghs_sda
//#pragma ghs section sdata=default
#endif

#else
	#error "Relocation to QM sections is compiler-dependent. The pragma used in this file work only with GHS compiler."
#endif
```

I got an error that indicates "returned non-zero exit status 1"

Is there any solution or at least a way to ignore this case ?

**Comment by eliben** [comment]
You should generally try to parse already preprocessed code with pycparser. See https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/ for more details.

In your example it's not clear where the error is coming from, it's not part of the snippet. If following the instructions in the link above doesn't work for you, please provide a complete minimal reproducer (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Arfaoui-Mahdi** [comment]
Thanks for your reply and for your time,
I already read your article about passing pre-processed code, that's why I used fake libs and I alternated between using gcc/cpp/clan -E, but always the same problem since that code is processed with GHS.

To clarify my point, the error from my code is coming exactly from the "#error" directive
![image](https://user-images.githubusercontent.com/53017181/111646816-455d8100-8802-11eb-89ff-564059c5e464.png)

where the code is : 

![image](https://user-images.githubusercontent.com/53017181/111647032-6e7e1180-8802-11eb-95fb-4a66e44ebf1b.png)


I don't dispose of the GHS compiler, can I use it with pycparser ?

**Comment by eliben** [comment]
Sorry, I don't follow. If you run your code through the preprocessor, you should not have those `#ifdef`s in there any more. The error trace in your first screenshot suggests that the error comes from `gcc -E`, which is not pycparser's problem.

Can you please provide the smallest **preprocessed** C file that demonstrates the problem?

**Comment by Arfaoui-Mahdi** [comment]
Hi, sorry for the late response, I was out of town for some days,
here's the snippet of what gcc give as an output : 

![image](https://user-images.githubusercontent.com/53017181/112330880-bd232400-8cb8-11eb-9838-aac9a77e089f.png)

it catches the "else" field which has the #error directive, is there any way to exclude this.

I have also another issue : 
I already have the problem of "__attribute__" while trying to parse the C project with C parser and I have found your solution to add '-D__attribute__(x)=' in the preprocessing args. But now I have another similar problem which is I have in my code "__inline__" and pycparser throws error when trying to parse the project, here a screenshoot : 

![image](https://user-images.githubusercontent.com/53017181/112331801-8a2d6000-8cb9-11eb-9723-a9c5b347bb27.png)

which is this line of code : 

![image](https://user-images.githubusercontent.com/53017181/112331941-a16c4d80-8cb9-11eb-86cb-8d06f858fa1c.png)

How can i prevent Pycparser from throwing error in this case.
PS : sorry for hiding some paths and names because it's still on going/confidential project.
and thanks for your replies and your help.

**Comment by eliben** [comment]
Closing until a true reproducer can be provided. Screensots of code snippets won't do.

Please follow https://stackoverflow.com/help/minimal-reproducible-example
