### ISSUE TITLE
Big CFFI Issue

### ISSUE THREAD

**Issue by Josephiah** [eliben/pycparser#418]
Hi guys, I'm a github newbie so this is my first time posting on GitHub so please be nice and patient with me (or else I will go off on you).

I am using buildozer to compile a kivy app. The app successfully compiled. In order for my app to run as an apk on android, sys.flags.optimize (or pyoptimize) must equal 2. However, whenever sys.flags.optimize (or pyoptimize) is 2, the app fails and says

**ImportError: CFFI with optimize=2 fails due to pycparser bug.** 

The explanation as to why is given in _raw_api.py file from the Utils folder of the Crytpo module saying:

    # Starting from v2.18, pycparser (used by cffi for in-line ABI mode)
    # stops working correctly when PYOPTIMIZE==2 or the parameter -OO is
    # passed. In that case, we fall back to ctypes.
    # Note that PyPy ships with an old version of pycparser so we can keep
    # using cffi there.
    # See https://github.com/Legrandin/pycryptodome/issues/228
    if '__pypy__' not in sys.builtin_module_names and sys.flags.optimize == 2:
        raise ImportError("CFFI with optimize=2 fails due to pycparser bug.")

I will not be using Pypy. So @eliben that means the only way for my app to work is for Pycparser to work successfully when sys.flags.optimize is 2. Please help! And Thank you

**Comment by eliben** [comment]
This issue should be opened with the consumer library, not with pycparser. It's probably related to https://github.com/eliben/pycparser/pull/198, in which case it comes from incorrect use of pycparser. Feel free to read the discussion on that issue. In any case, there's nothing I can do about the report at this point.
