### ISSUE TITLE
Add a parent attribute for Node, add Comment Node

### ISSUE THREAD

**Issue by deadlocklogic** [eliben/pycparser#424]
As the title says, why not adding a `parent` attribute for `Node`: it would be much easier when navigating the ast backwards.
And also why not preserve the comments with a `Comment` **Node**.
It should be pretty straightforward.

**Comment by deadlocklogic** [comment]
Currently I am doing a hack which is ugly but works:
```python
# Refactor to allow a parent attribute
class Node(object):
    __slots__ = ('parent')
...
```
```python
from c_ast import NodeVisitor


class ParentInjector(NodeVisitor):
    def __init__(self):
        self.parentStack = []

    def visit(self, node):
        node.parent = self.parentStack[-1] if len(self.parentStack) > 0 else None
        self.parentStack.append(node)
        result = super().visit(node)
        self.parentStack.pop()
        return result
```
And then visit the ast with `ParentInjector` as visitor

**Comment by eliben** [comment]
https://github.com/eliben/pycparser/wiki/FAQ#why-dont-ast-nodes-in-pycparser-have-parent-links
