### ISSUE TITLE
Using pycparser to analyse code style errors

### ISSUE THREAD

**Issue by busybox11** [eliben/pycparser#444]
Hello,
I'm trying to use pycparser in a project that, as described in the title of the issue, is able to analyse code style and detect code style errors in a bunch of C files.
For this, I'm trying to use a generated AST file that should be able to do this, according to a friend of mine who knows pretty well baout C and AST files.

Though, I have two problems with this project.
The first is that I can't find any way to detect trailing whitespaces in the AST file, nor how to configure / edit pycparser to do that. Is this possible, and if it is, could you help me on that?

Also, with some files, I get a ParseError, thus the AST cannot be generated.
After some debugging I found out that it only occurs with files that use the `write` function, so that means the `unistd.h` library.
Since I don't care about libraries and only about code style, is it possible to skip importing the library and only analyse the structure of the file?

I hope that you will be able to help me.
Thanks for creating this awesome library, and keep up the good work.

**Comment by eliben** [comment]
Regarding your first question - I have no idea what "the AST file" is, and how trailing whitespace affects anything. Could you clarify with a minimal example?

As for your second question, you should read [this blog post](https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/) in detail before you proceed.
