### ISSUE TITLE
"Preserve" headers when transforming code

### ISSUE THREAD

**Issue by aubertc** [eliben/pycparser#451]
_I have asked this question [in the pycparser-fake-libc  repo](https://github.com/ThomasGerstenberg/pycparser-fake-libc/issues/3#issue-1091664905), but I am not sure it was the appropriate place to ask this question._

I understand that fake headers are required to parse code sometimes, as explained e.g. in https://github.com/eliben/pycparser/issues/426, https://github.com/eliben/pycparser/issues/410, https://github.com/eliben/pycparser#32what-about-the-standard-c-library-headers or https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers

My problem is that, if I understand correctly, when using pycparser-fake-libc, e.g. `#include <stdio.h>` is replaced by a bunch of `typedef`. 
Now, I use pycparser to perform source code manipulation, and I would like the output to contain  `#include <stdio.h>` re-instated instead of the list of `typedef`.

An example is given at https://github.com/ThomasGerstenberg/pycparser-fake-libc/issues/3, I would like to know if there is a "standard" way of achieving this with pycparser, or if I need to fallback on e.g. some sed manipulation of my output source code.

**Comment by eliben** [comment]
Unfortunately, I don't think I have a better answer than https://github.com/eliben/pycparser/issues/137#issuecomment-240480353 - which you've already encountered.

pycparser tries to reduce scope to a single thing and do it well - parse C code.

**Comment by aubertc** [comment]
Ok thanks!
