### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by martinrotter** [eliben/pycparser#453]
This results in failure of `python2-pycparser` AUR/ARCH package:
```
Generating LALR tables
WARNING: 79 shift/reduce conflicts
WARNING: 37 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 27 resolved using rule (type_specifier -> atomic_specifier)
WARNING: rejected rule (empty -> <empty>) in state 27
WARNING: reduce/reduce conflict in state 87 resolved using rule (type_specifier -> atomic_specifier)
WARNING: rejected rule (empty -> <empty>) in state 87
WARNING: reduce/reduce conflict in state 437 resolved using rule (statement -> pppragma_directive)
WARNING: rejected rule (empty -> <empty>) in state 437
.....F............................................................................................................................
======================================================================
FAIL: test_all_examples (tests.test_examples.TestExamplesSucceed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/makepkg/python2-pycparser/src/pycparser-release_v2.21/tests/test_examples.py", line 29, in test_all_examples
    rc, 0, 'example "{}" failed with stdout =\n{}'.format(filename, stdout))
AssertionError: example "using_gcc_E_libc.py" failed with stdout =


```

**Comment by samoylenkodmitry** [comment]
same problem
```
copying pycparser/__init__.py -> build/lib/pycparser
creating build/lib/pycparser/ply
copying pycparser/ply/ygen.py -> build/lib/pycparser/ply
copying pycparser/ply/yacc.py -> build/lib/pycparser/ply
copying pycparser/ply/lex.py -> build/lib/pycparser/ply
copying pycparser/ply/ctokens.py -> build/lib/pycparser/ply
copying pycparser/ply/cpp.py -> build/lib/pycparser/ply
copying pycparser/ply/__init__.py -> build/lib/pycparser/ply
copying pycparser/_c_ast.cfg -> build/lib/pycparser
==> Starting check()...
Generating LALR tables
WARNING: 79 shift/reduce conflicts
WARNING: 37 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 27 resolved using rule (type_specifier -> atomic_specifier)
WARNING: rejected rule (empty -> <empty>) in state 27
WARNING: reduce/reduce conflict in state 87 resolved using rule (type_specifier -> atomic_specifier)
WARNING: rejected rule (empty -> <empty>) in state 87
WARNING: reduce/reduce conflict in state 437 resolved using rule (statement -> pppragma_directive)
WARNING: rejected rule (empty -> <empty>) in state 437
.....F............................................................................................................................
======================================================================
FAIL: test_all_examples (tests.test_examples.TestExamplesSucceed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/makepkg/python2-pycparser/src/pycparser-release_v2.21/tests/test_examples.py", line 29, in test_all_examples
    rc, 0, 'example "{}" failed with stdout =\n{}'.format(filename, stdout))
AssertionError: example "using_gcc_E_libc.py" failed with stdout =


----------------------------------------------------------------------
Ran 130 tests in 0.655s

FAILED (failures=1)
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: python2-pycparser
```
this occurs when trying to install from Arch repository https://archlinux.org/packages/extra/any/python-pycparser/

**Comment by eliben** [comment]
Can you reproduce this by checking out pycparser from this repository and running tests (with `-m unittest discover`) in its root dir?

**Comment by eliben** [comment]
... and if possible please use the latest version I just pushed; it has slightly improved debugging output in case of failures in this test.

I suspect your machine may not have `gcc` installed (and is a Linux), which may mess with this specific test.

**Comment by AlSmithAU** [comment]
Same issue with Manjaro AUR/ARCH package, gcc 11.1.0-3 and gcc-libs 11.1.0-3 installed by default. Running the test from the version on this repository:
```
python -m unittest discover                                                                                              ✔ 
Generating LALR tables
WARNING: 79 shift/reduce conflicts
WARNING: 37 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 33 resolved using rule (type_specifier -> atomic_specifier)
WARNING: rejected rule (empty -> <empty>) in state 33
WARNING: reduce/reduce conflict in state 70 resolved using rule (type_specifier -> atomic_specifier)
WARNING: rejected rule (empty -> <empty>) in state 70
WARNING: reduce/reduce conflict in state 365 resolved using rule (statement -> pppragma_directive)
WARNING: rejected rule (empty -> <empty>) in state 365
..................................................................................................................................
----------------------------------------------------------------------
Ran 130 tests in 3.731s

OK
```
So I'm taking that to mean it's an issue in the version in the AUR repository and we can either update from this version or wait for AUR to be updated.

**Comment by martinrotter** [comment]
> ... and if possible please use the latest version I just pushed; it has slightly improved debugging output in case of failures in this test.
> 
> I suspect your machine may not have `gcc` installed (and is a Linux), which may mess with this specific test.

You suspect wrong:
```
gcc --version
gcc (GCC) 11.1.0
```

Also, I cannot just "use latest version" because that is AUR package.

**Comment by martinrotter** [comment]
Tested with latest master:
```

.....F............................................................................................................................
======================================================================
FAIL: test_all_examples (tests.test_examples.TestExamplesSucceed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/makepkg/python2-pycparser/src/pycparser-release_v2.21/tests/test_examples.py", line 29, in test_all_examples
    rc, 0, 'example "{}" failed with stdout =\n{}'.format(filename, stdout))
AssertionError: example "using_gcc_E_libc.py" failed with stdout =


----------------------------------------------------------------------
Ran 130 tests in 0.768s

FAILED (failures=1)

```

**Comment by monakez** [comment]
i confirm having same issue with recent github repo.
i also installing it from AUR package and have exactly same error as issue reporter:
`
..(actually same output about LALR tables)...
======================================================================
FAIL: test_all_examples (tests.test_examples.TestExamplesSucceed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/graz/.cache/yay/python2-pycparser/src/pycparser-release_v2.21/tests/test_examples.py", line 29, in test_all_examples
    rc, 0, 'example "{}" failed with stdout =\n{}'.format(filename, stdout))
AssertionError: example "using_gcc_E_libc.py" failed with stdout =
`

and gcc is:
`
gcc --version
gcc (GCC) 11.1.0

`
OS:
`
uname -a
Linux omen 5.15.14-xanmod1-1 #1 SMP Fri, 14 Jan 2022 12:00:00 +0000 x86_64 GNU/Linux
`

**Comment by eliben** [comment]
> 

This is not using the latest master, which would print out the `stderr` as well.

Perhaps a new version of pycparser needs to be released for the packaging on AUR to pick it up, but this is no way to debug this thing...

I think this is a problem that needs to be reported to the folks who package pycparser for AUR; they should be able to very easily verify why exactly this test is failing. Generally, I do not recommend running the example tests when installing from packages - these tests are there just to test that pycparser's examples keep working; they're not helpful for installed packages.

I'm going to close this issue, unless someone provides a concrete reproducer that doesn't involve AUR - something I can try locally.
