### ISSUE TITLE
it generates different ast graphs from the clang -ast-dump

### ISSUE THREAD

**Issue by freexxxyyy** [eliben/pycparser#457]
Hi,
I am new to ast analysis. But when I use pycparser to generate the ast graphs by pycparser and clang, it gives different results.
The source code is

> int main() {
  foo();
  return 0;
}

using the command "python examples/dump_ast.py examples/c_files/basic_new.c", the ast is
![Screenshot from 2022-03-22 14-30-12](https://user-images.githubusercontent.com/10864295/159579537-155e2183-fa25-4818-bdc4-cbe0beea2208.png)

  
using "clang -Xclang -ast-dump -fsyntax-only examples/c_files/basic_new.c", the ast is
![Screenshot from 2022-03-22 14-30-05](https://user-images.githubusercontent.com/10864295/159579602-b33d191c-eebf-44be-9c64-b7e1d05f5d0f.png)

even filtering staff, such as " 0x14e1040 <col:10> ". The structs of two ast trees are different. by pycparser, it is "funcdef" nodes with two child nodes "decl" and "compound",, by clang, it is "functiondecl" nodes with one child node "compoundstmt. Even if only considering the path to call foo(), it is different: by pycparser, it is "FuncDef" ->"Compound"->"FuncCall"->"ID: foo". by clang, it is "FunctionDecl"->"CallExpr"->"ImplicitCastExpr"->"DeclRefExpr"-> 'foo' 'int ()'.
Can you give me some gudiance on it?
Thanks

**Comment by eliben** [comment]
There is no standardized format for representing ASTs, as far as I know. Each tool typically has its own. It should be fairly easy to convert between them, if needed.
