### ISSUE TITLE
How to parse JNI

### ISSUE THREAD

**Issue by wws86** [eliben/pycparser#461]
i try to parse some **`jni.c`** ,but seem can not detect the rtnType: 
```
pycparser.plyparser.ParseError: data.cpp:34:1: before: Java_com_ibm_cuda_CudaEvent_create
```
data.cpp:33-36 lines 
```
jlong JNICALL
Java_com_ibm_cuda_CudaEvent_create
  (JNIEnv * env, jclass, jint deviceId, jint flags)
{
```
how to parse jni by pycparser?

**Comment by eliben** [comment]
I'm not sure what `jni.c` is, but the standard guide on getting pycparser to parse some large corpus of C code is https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers/

Also check out the README and the Wiki of this repo for additional information
