### ISSUE TITLE
BUG: pycparser fails on missing docstrings under python -OO

### ISSUE THREAD

**Issue by pbrod** [eliben/pycparser#463]
When trying to bytecompile pycparser with the -OO option using cx_freeze/py2exe
the _create_param_rules function on line 129 https://github.com/eliben/pycparser/blob/6a7edee64c13d06e02b5eef554d9d6d10dcb71c0/pycparser/plyparser.py#L129
crashes because

     func.__doc__ is None.

The reason is that Python code byte-compiled with -OO has doc-strings stripped out (i.e. docstrings are None).

This creates problems for pycparser when the function _create_param_rules tries to extract the properties from the documentations of the func function.

A simple fix to this problem is to replace line 129 with:

    if func.__doc__ is not None:
        param_rule.__doc__ = func.__doc__.replace('xxx', xxx).replace('yyy', yyy)

See also:
http://bugs.python.org/issue23189#
http://stackoverflow.com/questions/22299532/unsupported-operand-types-for-nonetype-and-str-winappdbg-error-after-c

**Comment by eliben** [comment]
Please see the note in https://github.com/eliben/pycparser#21prerequisites

And #198 for more details
