### ISSUE TITLE
Add support for CPython 3.11

### ISSUE THREAD

**Issue by erlend-aasland** [eliben/pycparser#468]
Python 3.11-rc1 was just released. Final release is due in early October.

See [PEP-664](https://peps.python.org/pep-0664/)

**Comment by eliben** [comment]
Could you clarify what you mean by "add support for CPython 3.11"?

Did you try it with the RC and encounter issues?

**Comment by erlend-aasland** [comment]
Sorry for not being clear. What I meant was that it would be nice if Python 3.11 was added to the list of supported Python versions. I have not encountered issues with the RC.

**Comment by erlend-aasland** [comment]
🏓 Python 3.11 was released yesterday.
