### ISSUE TITLE
Pycparser.plyparser.ParseError: ngx_epoll_module.c: before: ngx_unit_t

### ISSUE THREAD

**Issue by kunzeng-ch** [eliben/pycparser#470]
Hello! I ran the codes: ast = parse_file('ngx_epoll_module.c', use_cpp=True,cpp_path=r'D:\MinGW\mingw64\bin\gcc.exe',cpp_args=['-E', r'-I fake_libc_include']), but I got the error:Pycparser.plyparser.ParseError: ngx_epoll_module.c: before: ngx_unit_t. Can you help me solve the problem?
Here is the code file.
[ngx_epoll_module.zip](https://github.com/eliben/pycparser/files/9412211/ngx_epoll_module.zip)

**Comment by eliben** [comment]
Please read section 3 in the README carefully, and read the blog post it links to

https://github.com/eliben/pycparser#3using
