### ISSUE TITLE
Parsing fails if type is not defined

### ISSUE THREAD

**Issue by Diegovsky** [eliben/pycparser#490]
I'm wiritng a quick script to help me write bidings to C stuff. One of the things I noticed is the parser fails if a type is not defined. Why is that? It can reasonably be known tokens in certain positions are types.

Here's an example from gobject introspection:
```c
const gchar * g_function_info_get_symbol (GIFunction* info);
```
Here's the error:
```python
Traceback (most recent call last):
  File "/home/diegovsky/Projects/gintro/tozigfn.py", line 83, in <module>
    show_func_defs(string)
  File "/home/diegovsky/Projects/gintro/tozigfn.py", line 69, in show_func_defs
    ast = CParser().parse(string)
  File "/usr/lib/python3.10/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/usr/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.10/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/usr/lib/python3.10/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :1:13: before: *
```

It fails. If I add some blank typedef's at the start, however, it works:
```c
typedef void GIFunction;
typedef char gchar;

const gchar * g_function_info_get_symbol (GIFunction* info);
```

Why is that? Can I tell the `CParser` to ignore such errors? My objective with this script is just to rewrite those declarations in another language, Zig:

```zig
// input: 
// typedef void GIFunction;
// typedef char gchar;
// 
// const gchar * g_function_info_get_symbol (GIFunction* info);
pub fn functionInfoGetSymbol(self: Self) *const gchar {
	return C.g_function_info_get_symbol(self.raw);
}
```

I can get the C flags from `pkgconfig` if that helps.

**Comment by eliben** [comment]
Please make sure to read the README file carefully starting with https://github.com/eliben/pycparser#3using

**Comment by Diegovsky** [comment]
Oh, I have read it. I'm not using an include for this.

I'm asking if it would be possible not to require types to be previously defined before.

**Comment by eliben** [comment]
Quoting from section 3.2 in the README:

> 
> The key point to understand here is that pycparser doesn't really care about the semantics of types. It only needs to know whether some token encountered in the source is a previously defined type. This is essential in order to be able to parse C correctly.
> 
> See [this blog post](https://eli.thegreenplace.net/2015/on-parsing-c-type-declarations-and-fake-headers) for more details.

Please read the linked blog post. It explains why pycparser has to know which tokens are types.

**Comment by Diegovsky** [comment]
I see, thank you for your time and patience :)
