### ISSUE TITLE
c_generator returning a dict mapping the nodes to their position in the resulting code

### ISSUE THREAD

**Issue by FlorianDyck** [eliben/pycparser#509]
I've built a [c_generator returning a dict mapping the nodes to their position in the resulting code](https://github.com/FlorianDyck/pycparser/blob/master/pycparser/position_c_generator.py) for a project where I needed the feature.
If you are interested, I could create a pull request.
If so, please decide wether this should replace the current c_generator.

**Comment by eliben** [comment]
The C generator part of pycparser is more of a demonstration than something I'd expect to be industrial-strength. If you can build alternative generators based on pycparser, that's great - by design.
