### ISSUE TITLE
Enable OpenSSF Scorecard Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [eliben/pycparser#512]
Hi again,

I'd like to suggest a tool that might help on tracking supply-chain security practice improvements, which is the [OpenSSF Scorecard Action](https://www.github.com/ossf/scorecard-action)

It proactively runs the [Scorecard](https://github.com/ossf/scorecard) on the repository and warn you in case of any Security Practice that may have changed (example: a new workflow was created without top level permissions).

The action has been adopted by 1800+ projects, having some prominent users such as [Tensorflow](https://github.com/tensorflow/tensorflow), [Angular](https://github.com/angular/angular), [Flutter](https://github.com/flutter/flutter), [sos.dev](https://sos.dev/) and [deps.dev](https://deps.dev/).

Would you be interested in a PR which adds this Action? Optionally it can also publish your results to the OpenSSF REST API, which allows a [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/) with the project's score to be added to its README.

Example: 
![image](https://github.com/eliben/pycparser/assets/22223372/2794a259-5272-4ebf-af5a-ff661d2303c6)

In case of doubts or concerns you can try to check [Scorecards FAQ](https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions). Anyway, feel free to reach me out, I'll be happy to help or gather feedback.

**Comment by eliben** [comment]
I've looked at https://api.securityscorecards.dev/projects/github.com/eliben/pycparser and ISTM that some of the criteria it uses are not a great fit for a project with essentially a single maintainer (e.g. "number of unreviewed commits", or "maintained" by counting recent changes). In general, maintaining a high score seems more work to appease an arbitrary metric than actually improve the security in the specific case of pycparser.

**Comment by joycebrum** [comment]
Thanks for the return eliben! Yeah, unfortunately some of these metrics are unfeasible to single maintainers.
