### ISSUE TITLE
Can't parse incomplete types and other syntactically valid but non-compilable code

### ISSUE THREAD

**Issue by geajack** [eliben/pycparser#517]
I'd like to be able to parse this declaration:

```c
int SDL_GetPointDisplayIndex(const SDL_Point *point);
```

Now of course, this won't compile unless I put in a typedef for `SDL_Point`, but I still feel like I should be able to parse it and get an AST, even if it won't compile. Shouldn't the parser at least be able to infer that `SDL_Point` is some kind of type and keep going?

**Comment by eliben** [comment]
See https://eli.thegreenplace.net/2007/11/24/the-context-sensitivity-of-cs-grammar/ and https://eli.thegreenplace.net/2011/05/02/the-context-sensitivity-of-cs-grammar-revisited/
