### ISSUE TITLE
ParseError with typeof

### ISSUE THREAD

**Issue by sertonix** [eliben/pycparser#554]
pycparser seems to be unable to parse `typeof` (or `__typeof__`). For example this code

```C
typedef __typeof__(int *) test;
```
fails to compile with this error
`pycparser.plyparser.ParseError: c_files/test.c:2:27: before: test`
but is valid C code.

Doc: https://gcc.gnu.org/onlinedocs/gcc/Typeof.html

**Comment by eliben** [comment]
Is it ISO C or a gcc extension?

**Comment by sertonix** [comment]
The gcc doc states that __typeof__ is OSI C. I can't find the OSI C spec to verify it.

**Comment by eliben** [comment]
For gnu extension support, consider https://github.com/inducer/pycparserext
