### ISSUE TITLE
dirent DIR typedef

### ISSUE THREAD

**Issue by MegaManSec** [eliben/pycparser#557]
Hi,

Thanks for this project, it's really helpful.

I'm trying to work out how to best contribute a new typedef in `fake_libc_include`.

I have a C program that uses `dirent.h`'s `DIR` typedef. pycparser doesn't seem to be able to pick up the include in my C file to understand the typedef.

The problem is, I'm unsure how to add it to `fake_libc_include`, as `DIR` can either be a typedef for the __dirdesc struct, or a void pointer. Obviously for my machine, the __dirdesc struct is fine, but I'm unsure whether this project prefers Linux.

On my FreeBSD machine, `/usr/include/dirent.h` defines `DIR` as:

```c
#if __BSD_VISIBLE

typedef struct _dirdesc DIR;

#else /* !__BSD_VISIBLE */

typedef void *  DIR;

#endif /* __BSD_VISIBLE */
```

Thank you.

**Comment by eliben** [comment]
It doesn't really matter what type you actually assign it to. pycparser doesn't do semantic analysis - it's only parsing, so all it needs to know is that some identifier *is a type at all*. Look at the current `_fake_typedefs.h` - they all pretty much alias the types to `int`

**Comment by MegaManSec** [comment]
Understood; thank you!
