### ISSUE TITLE
parsing "const char* const*" generates "const char ** const"

### ISSUE THREAD

**Issue by schachmat** [eliben/pycparser#68]
Heyho,

I use pycparser to automatically implement a given inteface with stub functions. One function takes a const char* const* argument and after parsing this declaration, appending the body and generating it with defaults, I get a const char ** const argument in my implementation. This leads to a "warning: assignment from incompatible pointer type" from gcc.

I have two cases leading to this warning:
parsed -> generated
const char* const* arg -> const char ** const arg
struct bla* const* arg -> struct bla ** const arg

--schachmat

**Comment by eliben** [comment]
Thanks for the report. Can you provide a full test case using the pycparser API? I assume you're using the C code generator as well?

**Comment by schachmat** [comment]
Here you go:

bla.c: `int test(const char* const* arg);`

test.py:

    #!/bin/env python
    
    import sys
    from pycparser import parse_file, c_generator, c_ast
    
    sys.path.extend(['.', '..'])
    
    class FuncDeclVisitor(c_ast.NodeVisitor):
        def visit_FuncDecl(self, node):
            decl = c_ast.Decl("hui", None, None, None, node, None, None)
            print(c_generator.CGenerator().visit(decl))
    
    ast = parse_file("bla.c", use_cpp=True, cpp_args=[r'-Ifake', r'-I.'])
    FuncDeclVisitor().visit(ast)

output when running test.py is: `int test(const char ** const arg)`
expected output is: `int test(const char * const * arg)`

**Comment by eliben** [comment]
Hmm, curiously pycparser's cdecl also gets this wrong:

    $python examples/cdecl.py "const char* const* arg;"
    Explaining the declaration: const char* const* arg;

    arg is a const pointer to pointer to const char

And:

    $ python examples/cdecl.py "const char** const arg;"
    Explaining the declaration: const char** const arg;

    arg is a pointer to const pointer to const char
