### ISSUE TITLE
Parse not work with FILE pointer

### ISSUE THREAD

**Issue by centaurialpha** [eliben/pycparser#71]
Hello!
I'm using pycparser to generate the symbol tree in an IDE. The problem is when used the FILE pointer. For example:
```python
code = """
FILE * fp;
void foo( void ) {
return;
}
"""

parser = c_parser.CParser()
ast = parser.parse(code)
```
traceback

```
ParseError: :2:6: before: *
```

**Comment by kirbyfan64** [comment]
You need to include the "fake" libc headers; FILE is defined there.

**Comment by centaurialpha** [comment]
Please can you give me an example?

**Comment by kirbyfan64** [comment]
See [here](https://github.com/eliben/pycparser/blob/master/examples/using_cpp_libc.py) for setting up pycparser's fake headers and include `stdio.h` in your C fakr.

**Comment by kirbyfan64** [comment]
See [here](https://github.com/eliben/pycparser/blob/master/examples/using_cpp_libc.py) for setting up pycparser's fake headers and include `stdio.h` in your C file.

**Comment by centaurialpha** [comment]
Thank you very much, then i have to use parse_file instead of c_parser.
