### ISSUE TITLE
pycparser increases memory usage of pyOpenSSL by an order of magnitue

### ISSUE THREAD

**Issue by ianw** [eliben/pycparser#72]
I have opened https://github.com/pyca/pyopenssl/issues/202 which shows the rewrite of pyOpenSSL from C bindings to it's current usage of "cryptography" (the package) between 0.13 & 0.14 has increased memory usage by an order of magnitude from ~2mb to ~20mb

The issue was debugged from issues with openstack ci jobs running out of memory in [1]

As described there, heapy showed the top heap usage as

```
Partition of a set of 205366 objects. Total size = 30969040 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  67041  33  5712560  18   5712560  18 str
     1  10260   5  2872800   9   8585360  28 dict of pycparser.plyparser.Coord
     2  27765  14  2367552   8  10952912  35 tuple
     3   1215   1  2246760   7  13199672  43 dict (no owner)
     4   1882   1  1972336   6  15172008  49 dict of pycparser.c_ast.Decl
     5  16085   8  1736232   6  16908240  55 list
     6    360   0  1135296   4  18043536  58 dict of module
     7   4041   2  1131480   4  19175016  62 dict of pycparser.c_ast.TypeDecl
     8   4021   2  1125880   4  20300896  66 dict of pycparser.c_ast.IdentifierType
     9   6984   3   893952   3  21194848  68 types.CodeType
<413 more rows. Type e.g. '_.more' to view.>
```

which seems to indicate pycparser as pretty uch the top consumer.  Of course there are many layers here -- pyOpenSSL -> cryptography -> cffi -> pycparser

I am not sure if something is tickling a bug in pycparser and causing leakage, or if this is just expected usage.  The increase is rather dramatic however.

I understand this isn't a great bug report.  I haven't a regression point where things suddenly started using more memory and it may be something one of the upper layers is doing wrong.

[1] https://etherpad.openstack.org/p/oom-in-rax-centos7-CI-job

**Comment by eliben** [comment]
Thanks for reporting.

I'll be happy to try to help, but I'll really need a better bug report here :) The usage of pycparser has to be isolated from this stack, and then I can try and see if memory usage is reasonable and can be reduced.

This can end up being a simple matter of a very large job given to pycparser which results in a large AST that consumes a lot of memory, but more data is needed to determine where the fault is.

**Comment by ianw** [comment]
I instrumented pycparser to dump out whatever it was parsing and it seems to account for the increased memory usage.

pycparser is getting [1] from cryptography->ffi and this pretty much accounts for the increased memory usage

```
ubuntu@ubuntu:/tmp$ cat test.py
import time

from pycparser import c_parser, parse_file

print "starting"
time.sleep(5)

parse_file('/tmp/file.c')
print "parsed"

time.sleep(10)
```

```
ubuntu@ubuntu:/tmp$ python ./test.py 
starting
^Z
[1]+  Stopped                 python ./test.py

ubuntu@ubuntu:/tmp$ ps -eo pid,rss,pmem,cmd  | grep [p]ython
13922  6392  1.2 python ./test.py

ubuntu@ubuntu:/tmp$ fg
python ./test.py
parsed
^Z
[1]+  Stopped                 python ./test.py

ubuntu@ubuntu:/tmp$ ps -eo pid,rss,pmem,cmd  | grep [p]ython
13922 20992  4.1 python ./test.py
```

if this is reasonable or not, given the input, i'm not sure

[1] http://paste.openstack.org/show/197640/

**Comment by ianw** [comment]
For reference of how it seems to get this; the bindings defined in _modules at [1] are collected together in [2]  where the ```TYPES``` ```FUNCTIONS``` and ```MACROS``` for each binding are eventually sent down to ```ffi.cdef``` which makes its way to ```pycparser```

```python

    for name in modules:
        module_name = module_prefix + name
         ...
        types.append(module.TYPES)
        macros.append(module.MACROS)
        functions.append(module.FUNCTIONS)

ffi = build_ffi(cdef_source="\n".join(types + functions + macros))

...

def build_ffi(cdef_source, verify_source, libraries=[], extra_compile_args=[],
              extra_link_args=[]):
    ffi = FFI()
    ffi.cdef(cdef_source)
```

[1] https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/bindings/openssl/binding.py#L65
[2] https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/bindings/utils.py#L44

**Comment by rbtcollins** [comment]
So the question in this context, AIUI, is whether this memory use is excessive to parse the bindings for OpenSSL.

If the memory use is excessive fine. But what I'm curious about is whether the AST is freed once the bindings are compiled and symbols resolved, or if the AST is being kept around indefinitely.

**Comment by eliben** [comment]
@ianw so it's 14 MB of memory used for that 2K-line header file? I wouldn't say this is completely outlandish - this is Python, and memory usage is quite high. It's possible that this can be reduced - I've never really attempted to micro-optimize pycparser's memory usage. But I don't see a disaster here either (no non-linear increase, no crazy usage).

There's much that can be done, but I don't have much free time to spend on memory optimizations right now. Patches are welcome though :)

**Comment by haypo** [comment]
You may play with https://pytracemalloc.readthedocs.org/ to see exactly which lines allocate memory. The module is now part of Python 3.4.

**Comment by eliben** [comment]
Thanks for the tip @haypo -- I used to use heapy for this before, but tracemalloc being built-in is way more convenient.

**Comment by eliben** [comment]
@ianw check out the newly committed version. I use `__slots__` in AST nodes to make them as small as possible, and this helps somewhat.

However, this may not affect peak memory usage too much (down from 21MB to 17.5MB on my machine), because the parser itself and the lexer use a bunch of memory while doing their thing - it's inside PLY, so I don't control it. But once the parsing is done, the memory consumed by the AST nodes should be much lower.

According to heapy, the memory consumption of the result is 33% lower after this change (not peak memory).

I'll keep this issue open for now - can you run some tests and verify that memory consumption is lower now?

**Comment by eliben** [comment]
After some more poking with `heapy`, I've reduced the size of the result AST by ~15% and the max RSS for the sample file goes down by another ~1MB.

**Comment by eliben** [comment]
Closing this - the recent changes should have reduced pycparser's memory usage considerably.
