### ISSUE TITLE
Support for Weakref in __slots__

### ISSUE THREAD

**Issue by gdanezis** [eliben/pycparser#76]
Hello,
I see you added support for the __slots__ mechanism in the ast. Nice. However, this breaks cffi downstream, since they use weak references to Enum, etc objects (see their cparser.py file). In turn this breaks petlib which I maintain.
I think the solution is to include the "__weakref__" in the "__slots__" list of fields, as per the advice at:
https://docs.python.org/2/reference/datamodel.html#slots
Many thanks,
George

**Comment by eliben** [comment]
Thanks for letting me know. I'll take a look

**Comment by alex** [comment]
This is not cryptography specific, this is any use of cffi, as far as I can tell, cryptography is just the most popular :-)

**Comment by eliben** [comment]
Fixed, I believe.

It's kinda scary how much breakage a new release can cause in a short time. I don't (and can't) run th testsuites of all projects dependent on pycparser for each release. I would advise cffi and other projects to lock their dependency on a "known-good" pycparser release and bump it occasionally after testing explicitly. This sounds like a more prudent approach with any dependency.

**Comment by eliben** [comment]
Can someone verify that (at least some of) the downstream projects are fixed with this change? I will release a new version then with just this fix, so that `pip install pycparser` does the right thing

**Comment by reaperhulk** [comment]
I can confirm that master fixes the issue for cffi.

**Comment by eliben** [comment]
Thanks, @reaperhulk

**Comment by cboylan** [comment]
I can install cryptography with this change to pycparser in place.

**Comment by eliben** [comment]
Pushed a fix release (2.12) to PyPI

**Comment by dhellmann** [comment]
Thanks!

**Comment by fermayo** [comment]
wow, that was fast, thanks!

**Comment by eliben** [comment]
@fermayo more like lucky, as I'm off to a 3-day off-line vacation tomorrow :-)

I hope cffi fixes their deps....
