### ISSUE TITLE
Slow parse using python ConfigParser and requests

### ISSUE THREAD

**Issue by mcarli** [eliben/pycparser#80]
I wrote a simple script in Python that read a config file (a ini format) and then using request library to make an HTTP request to my server.

When i'm using it on my Raspberry Pi i noticed a strange behavior: when i'm using ConfigParser and request libraries together Python have a strange delay into interpreting my script. If i comment the line that require "requests" all works correctly.

So i created a simple test file to debug this:

    $ cat test2.py
    import socket
    from socket import error as socket_error
    
    import requests
    
    import time
    
    from ConfigParser import SafeConfigParser

Linux time command on this code:

    $ time python test2.py
    real    0m21.763s
    user    0m21.260s
    sys     0m0.300s

If i will comment out "requests" require, this is the output:

    $ time python test2.py
    real    0m0.373s
    user    0m0.300s
    sys     0m0.070s

Library version:

    $ pip show requests
    ---
    Metadata-Version: 2.0
    Name: requests
    Version: 2.7.0
    Summary: Python HTTP for Humans.
    Home-page: http://python-requests.org
    Author: Kenneth Reitz
    Author-email: me@kennethreitz.com
    License: Apache 2.0
    Location: /usr/local/lib/python2.7/dist-packages
    Requires:

    $ pip show ConfigParser
    ---
    Metadata-Version: 1.1
    Name: configparser
    Version: 3.3.0.post2
    Summary: This library brings the updated configparser from Python 3.2+ to Python 2.6-2.7.
    Home-page: http://docs.python.org/3/library/configparser.html
    Author: Łukasz Langa
    Author-email: lukasz@langa.pl
    License: MIT
    Location: /usr/local/lib/python2.7/dist-packages
    Requires:

    $ pip show pycparser
    ---
    Metadata-Version: 1.1
    Name: pycparser
    Version: 2.12
    Summary: C parser in Python
    Home-page: https://github.com/eliben/pycparser
    Author: Eli Bendersky
    Author-email: eliben@gmail.com
    License: BSD
    Location: /usr/local/lib/python2.7/dist-packages
    Requires:

    $ python --version
    Python 2.7.3

This is the output of "python -v test2.py"

    [...]
    # /usr/lib/python2.7/pickle.pyc matches /usr/lib/python2.7/pickle.py
    import pickle # precompiled from /usr/lib/python2.7/pickle.pyc
    import marshal # builtin
    # /usr/local/lib/python2.7/dist-packages/pycparser/c_parser.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py
    import pycparser.c_parser # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/c_parser.pyc
    import pycparser.ply # directory /usr/local/lib/python2.7/dist-packages/pycparser/ply
    # /usr/local/lib/python2.7/dist-packages/pycparser/ply/__init__.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/ply/__init__.py
    import pycparser.ply # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/ply/__init__.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py
    import pycparser.ply.yacc # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/c_ast.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/c_ast.py
    import pycparser.c_ast # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/c_ast.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/c_lexer.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/c_lexer.py
    import pycparser.c_lexer # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/c_lexer.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/ply/lex.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/ply/lex.py
    import pycparser.ply.lex # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/ply/lex.pyc
    # /usr/lib/python2.7/copy.pyc matches /usr/lib/python2.7/copy.py
    import copy # precompiled from /usr/lib/python2.7/copy.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/plyparser.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py
    import pycparser.plyparser # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/plyparser.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/ast_transforms.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/ast_transforms.py
    import pycparser.ast_transforms # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/ast_transforms.pyc
    dlopen("/usr/local/lib/python2.7/dist-packages/_cffi_backend.so", 2);
    import _cffi_backend # dynamically loaded from /usr/local/lib/python2.7/dist-packages/_cffi_backend.so
    # /usr/local/lib/python2.7/dist-packages/pycparser/lextab.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/lextab.py
    import pycparser.lextab # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/lextab.pyc
    # /usr/lib/python2.7/encodings/latin_1.pyc matches /usr/lib/python2.7/encodings/latin_1.py
    import encodings.latin_1 # precompiled from /usr/lib/python2.7/encodings/latin_1.pyc
    # /usr/local/lib/python2.7/dist-packages/pycparser/yacctab.pyc matches /usr/local/lib/python2.7/dist-packages/pycparser/yacctab.py
    import pycparser.yacctab # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/yacctab.pyc
    [...]

Python interpreter hang some second to last lines of previuos output

    import pycparser.yacctab # precompiled from /usr/local/lib/python2.7/dist-packages/pycparser/yacctab.pyc

**Comment by eliben** [comment]
I have to admit I'm having a trouble parsing this bug report. Not sure what pycparser has to do with requests and ConfigParser.
