### ISSUE TITLE
Crases when tries to parse a cast to (FILE*) or definition of type FILE*

### ISSUE THREAD

**Issue by IIIypuk09** [eliben/pycparser#81]
example c_to_c crases with error 
  File "C:\Python34\lib\site-packages\pycparser\plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: .\c_files\main.c:53:18: before: )

main.c file is available here https://drive.google.com/file/d/0B0iD1x-xUUzoR2wzVW00ckNxdDQ/view?usp=sharing

Lines that raises the error, all caintain FILE*. This is standard type of file.

**Comment by kirbyfan64** [comment]
You need to include `stdio.h`.

**Comment by eliben** [comment]
Please review section 3 in the README carefully [https://github.com/eliben/pycparser#3using]
