### ISSUE TITLE
Not possible to serialize the AST

### ISSUE THREAD

**Issue by pakt** [eliben/pycparser#82]
`pickle.dump` can't handle ast because the `ast` class uses `__slots__` but doesn't implement `__getstate__`. 

It'd be useful to add that functionality. Use case: parse a large repository once and store the ast for further processing. This way the source tree is parsed only once, saving time.

**Comment by eliben** [comment]
Sounds good - feel free to send a pull request

**Comment by eliben** [comment]
Any updates here?

**Comment by chriscz** [comment]
For anyone actually trying to do this, in the meantime https://pypi.python.org/pypi/dill might be useful, I haven't tested whether it works, but there's a good chance it will.
