### ISSUE TITLE
function declarations are incorrect

### ISSUE THREAD

**Issue by ykram** [eliben/pycparser#88]
Example:

$ python c-to-c.py c_files/funky.c
char foo[)]
{
  return '1';
}

int maxout_in[)]
{
  char o = foo();
  return (((int) matrix[1][2]) * 5) - paste;
}

int main[)]
{
  auto char *multi = "a multi";
}

**Comment by eliben** [comment]
I cannot reproduce it in the master branch. Which version of pycparser are you using?
