### ISSUE TITLE
Error while preprocessing .c files with many -I options

### ISSUE THREAD

**Issue by vikas753** [eliben/pycparser#90]
File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\rfa_rf_wcdma_rf_mc.scons", line 295:

    gen_xml.parse_dir(['D:/builds/OfFTargetSetup/TA1_0TA10_offtarget_2015_05_14_00_21_20/modem_proc/rftech_wcdma/rf/mc/src'],env['CPPPATH'],env['INC_ROOT'])

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\gen_xml.py", line 261:

    debugs(c_file,conf_root,"log.txt",inc,general)

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\gen_xml.py", line 89:

    ast = parse_file(filename, use_cpp=True,cpp_path='gcc',cpp_args=cppargs)

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\pycparser\__init__.py", line 93:

    return parser.parse(text, filename)

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\pycparser\c_parser.py", line 146:

    debug=debuglevel)

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\pycparser\ply\yacc.py", line 265:

    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\pycparser\ply\yacc.py", line 971:

    p.callable(pslice)

  File "D:\Builds\OfFTargetSetup\TA1_0TA10_offtarget_2015_05_14_00_21_20\modem_proc\rftech_wcdma\rf\mc\build\pycparser\c_parser.py", line 583:

    body=p[4])

assert 'typedef' not in spec['storage']

**Comment by vikas753** [comment]
What is the reason for the above error?..programs are compiled and running succesfully..

**Comment by eliben** [comment]
This may be an issue with pycparser, but your bug report is very difficult to understand. Can you create a simple reproducer (preferably a single C file you get this failure on)

**Comment by vikas753** [comment]
#include "comdef.h"
#include "rfm_wcdma_ftm.h"
#include "rfwcdma_data.h"
#include "rfcom.h"
#include "rfcommon_msg.h"
#include "rfwcdma_core_util.h"
#include "rfm_wcdma.h"
#include "rfwcdma_core_txplim.h"

/*============================================================================*/
/*!
  @name Debug Flags

  @brief
  This section includes interfaces to update and query the debug flags used
  to WCDMA driver
*/
/*! @{ */

/*----------------------------------------------------------------------------*/
/*!
  @brief
  Get WCDMA debug flags

  @details
  This function will return WCDMA debug flags

  @return
  Writeable Pointer to WCDMA debug flags
*/
rfwcdma_data_debug_flags_type*
rfm_wcdma_ftm_get_debug_flags
(
  void
)
{

  return rfwcdma_get_debug_flags();

} /* rfm_wcdma_ftm_get_debug_flags */

/*! @} */

/*============================================================================*/
/*!
  @brief
  Get current RxAGC information

  @details
  This function can be called from FTM to get the current RxAGC information

  @param device 
  RFM device on which the RxAGC value is requested
  
  @param multicarrier_idx
  RF COM multicarrier id type indicating the number of active carriers

  @param agc_unit
  Unit for representation of RxAGC value

  @param agc_info
  Pointer to hold the RxAGC information

  @return
  Flag indicating the status of the AGC info request
*/
boolean
rfm_wcdma_ftm_get_rxagc_info
(
  uint8 device,
  uint8 multicarrier_idx,
  uint8 agc_unit,
  rfm_wcdma_ftm_rxagc_info *agc_info
)
{
  int16 rxagc_val_db10;

  if (agc_info == NULL)
  {
    RF_MSG_1(RF_LOW, "rfm_wcdma_ftm_get_rxagc_info :"
               "Info pointer passed is NULL - Dev %d", device );
     return FALSE;
  } /* if (agc_info == NULL) */

  agc_info->lna_state = rfwcdma_core_util_get_lna_state(device);
  
  rxagc_val_db10 = rfm_wcdma_get_rxagc( device, 
                                        RFCOM_SERVINGCELL_RXAGC,
                                        agc_unit,
                                        multicarrier_idx );   

  agc_info->rxagc_val = -1060 + rxagc_val_db10 + 512;

  RF_MSG_4( RF_HIGH, "rfm_wcdma_ftm: AGC Info requested on Device: %d, " 
            "Multicarrier index :%d. RxAGC Value is: %d dBm, LNA state is:%d",
            device, multicarrier_idx, agc_info->rxagc_val, agc_info->lna_state);

  return TRUE; 

} /* rfm_wcdma_ftm_get_rxagc_info */

/*------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Override the power limiting mode of operation
 
  @details
  This function overrides the PLIM loop to enable or disable mode
 
  @param device
  RFM Device on which PLIM is to be overriden
 
  @param plim_enable
  Flag indicating, if the PLIM is to be enabled
 
  @return
  Status of plim override
*/
boolean
rfm_wcdma_ftm_plim_override_mode
(
  rfm_device_enum_type device,
  boolean plim_enable
)
{
  return ( rfwcdma_plim_override_mode(device, plim_enable));
  
} /* rfm_wcdma_ftm_plim_override_mode */

/*------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Override TempComp to disable or enable mode
 
  @details
  This function will be used to override the TempComp mode of operation to disable.
 
  @param device
  RFM device on which the temp comp is to be overridden
 
  @param enable_tempcomp
  Flag indicating if the temp comp is to be disabled or not
 
  @return
  Flag indication status of TempComp override
*/
boolean
rfm_wcdma_ftm_temp_comp_override
(
  rfm_device_enum_type device,
  boolean enable_tempcomp
)
{
  boolean ret_val = TRUE;

  if ( enable_tempcomp == TRUE )
  {
    ret_val &= rfwcdma_tempcomp_override_enable(device);
    RF_MSG_1( RF_HIGH, "rfm_wcdma_ftm_temp_comp_override: TempComp Overridden to enable - "
                       "Device %d", device );
  } /* if ( enable_tempcomp == TRUE ) */
  else
  {
    ret_val &= rfwcdma_tempcomp_override_disable(device);
    RF_MSG_1( RF_HIGH, "rfm_wcdma_ftm_temp_comp_override: TempComp Overridden to disable - "
                       "Device %d", device );
  } /* if ! ( enable_tempcomp == TRUE ) */

  return ret_val;

} /* rfm_wcdma_ftm_temp_comp_override */


/*! @} */


The above is the one of the C-files where the code was giving the above bug report

**Comment by vikas753** [comment]
I can provide a sample .h file also ..

**Comment by eliben** [comment]
This is missing a ton of header files. Please **attach** a single preprocessed file.
