### ISSUE TITLE
in examples:cdecl.py

### ISSUE THREAD

**Issue by ivand58** [eliben/pycparser#93]
cdecl.py doesn't recognize the structure declaration, for e.g.
<code>
cdecl.py "struct P {int x; int y} p;"
</code>
returns 
<code>
return quals + _explain_type(decl.type)

TypeError: cannot concatenate 'str' and 'NoneType' objects
</code>

**Comment by eliben** [comment]
The cdecl sample wasn't designed to support inline struct declarations. Patches welcome
