### ISSUE TITLE
ParseError before: {

### ISSUE THREAD

**Issue by glandre** [eliben/pycparser#98]
Hello,

I'm using pycparser to simply get function name, and its coord. I created a class named CParser which extends c_ast.NodeVisitor (following func_def example), the parse method of this class I created is responsible to get such information. In addition to this information, this class also retrieves the body of each function (get_function_bodies method), by reading the file and, based on coord, consuming each line, which I use too.

It is working for several samples, but when I try to use it with a specific source code (grep source code) It gives me the following error:

Traceback (most recent call last):
```
  File "script/pycparser_adapter/CParser.py", line 121, in <module>
    c_file_parser.parse()
  File "script/pycparser_adapter/CParser.py", line 74, in parse
    ast = parse_file(file_path, use_cpp=self.use_cpp)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: grep.c:3821:38: before: {
```

I debugged de code and found that the line of the original 'grep.c' is as follows:
```
kwset->trie
    = (struct trie *) obstack_alloc(&kwset->obstack, sizeof (struct trie));
```
and in the preprocessed file it is like this:
```
kwset->trie
    = (struct trie *) __extension__ ({ struct obstack *__h = (&kwset->obstack); __extension__ ({ struct obstack *__o = (__h); int __len = ((sizeof (struct trie))); if (__o->chunk_limit - __o->next_free < __len) _obstack_newchunk (__o, __len); __o->next_free += __len; (void) 0; }); __extension__ ({ struct obstack *__o1 = (__h); void *value; value = (void *) __o1->object_base; if (__o1->next_free == value) __o1->maybe_empty_object = 1; __o1->next_free = (((((__o1->next_free) - (char *) 0)+__o1->alignment_mask) & ~ (__o1->alignment_mask)) + (char *) 0); if (__o1->next_free - (char *)__o1->chunk > __o1->chunk_limit - (char *)__o1->chunk) __o1->next_free = __o1->chunk_limit; __o1->object_base = __o1->next_free; value; }); });
```

The command I'm using to preprocess the code is:
```
$ gcc -E -Ipycparser/utils/fake_libc_include/ -I. grep.c > grep_pp.c
```

Which results in some warnings:
```
grep.c:4664:0: warning: "CALL_FREEFUN" redefined [enabled by default]
 #define CALL_FREEFUN(h, old_chunk) \
 ^
grep.c:4656:0: note: this is the location of the previous definition
 #define CALL_FREEFUN(h, old_chunk) \
```
Even though the grep_pp.c file is created properly.

I'm also capable to compile the source code without problems using the following command:
```
$ gcc -I. grep.c -o grep.exe
```
I would really appreciate if you could help me to find a solution to this parse error.

In order to help with some tests, I'm sharing in this link ([Dropbox Grep](https://goo.gl/h4JVP8)) the Python class I did, and also the grep source code, in which tested the commands I provided bellow. Additionally, to run the python class you can use the following command:
```
$ python script/pycparser_adapter/CParser.py grep.c pycparser/utils/fake_libc_include/ .
```
which means:
```
$ python script/pycparser_adapter/CParser.py <source file> [lib_dir1 [lib_dir2...]]
```
For example, to run using directly the preprocessed file, should be like:
```
$ python script/pycparser_adapter/CParser.py grep_pp.c
```

Thanks in advance,
Geraldo

**Comment by eliben** [comment]
Please see: https://github.com/eliben/pycparser/wiki/FAQ#what-do-i-do-about-__extension__

**Comment by kirbyfan64** [comment]
There's a section about this in the [FAQ]:

>**Does pycparser support GNU/Visual C++ extensions?**
> Mostly no. **pycparser** only knows how to parse ISO C99, and doesn't support compiler-specific extensions. This is a deliberate decision, which favors the simplicity and maintainability of the parser over additional features.
>
> Dedicated users should find it easy to extend **pycparser** to support any specific extension they're interested in. Actually, such projects already exist. See for example [**pycparserext**](https://github.com/inducer/pycparserext) by Andreas Klöckner, which extends **pycparser** to support GNU/GCC extensions.

**Comment by glandre** [comment]
Thank you @eliben and @kirbyfan64 very much for the support. 

I could solve the problem with a workaround.

Unfortunately, I tried *pycparserext* but it seems that it still doesn't support `__extension__`. I installed it here, and adapted my method to use `GnuCParser` while parsing the file. However, it still raising the error.

I also tried to define it in the preprocessed file, but, if I do simply as follows:
```
#define __extension__(x)
```
The parser returns the following error:
```
Traceback (most recent call last):
  File "script/pycparser_adapter/CParser.py", line 126, in <module>
    c_file_parser.parse()
  File "script/pycparser_adapter/CParser.py", line 79, in parse
    ast = parse_file(file_path, use_cpp=self.use_cpp)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: grep.c:3821:23: before: ;
```

...and if I try:
```
#define __extension__(x) x
```
it returns:
```
Traceback (most recent call last):
  File "script/pycparser_adapter/CParser.py", line 126, in <module>
    c_file_parser.parse()
  File "script/pycparser_adapter/CParser.py", line 79, in parse
    ast = parse_file(file_path, use_cpp=self.use_cpp)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: grep.c:3821:25: before: struct
```

so I tried:
```
#define __extension__(x) 1
```
Additionally, I needed to add:
```
#define wctype_t
```
... and at least I could parse the file.

This is the code *pycparser* and *pycparserext* are not comprehending:
```
link->trie = (struct trie *) __extension__ (
{
	struct obstack *__h = (&kwset->obstack); 
	__extension__ (
		{
			struct obstack *__o = (__h); 
			int __len = ((sizeof (struct trie))); 
			if (__o->chunk_limit - __o->next_free < __len)
				_obstack_newchunk (__o, __len); 
			__o->next_free += __len; 
			(void) 0;
		}
	); 
	__extension__ (
		{ 
			struct obstack *__o1 = (__h); 
			void *value; value = (void *) __o1->object_base; 
			if (__o1->next_free == value) 
				__o1->maybe_empty_object = 1;
			
			__o1->next_free = (((((__o1->next_free) - (char *) 0)+__o1->alignment_mask) & ~ (__o1->alignment_mask)) + (char *) 0); 
			
			if (__o1->next_free - (char *)__o1->chunk > __o1->chunk_limit - (char *)__o1->chunk) __o1->next_free = __o1->chunk_limit; __o1->object_base = __o1->next_free; value; 
		}
	); 

}

);
```

I am not familiar with C parsing yet, so I have no clue on how to work it around. I'm planning to use this class automatically with several source files, that's why I was trying to solve this problem.

So I think I'll need to manually put defines according to each file, right?

Thanks again for helping.

**Comment by eliben** [comment]
The reason you needed to define `__extension__` to something like `1` is that it's used as an expression in a cast. And yes, you'll have to define this for every translation unit you want to parse and has such usage of extensions.

**Comment by glandre** [comment]
OK @eliben, thank you very much. Solved my problem.
